
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

using MyGeneration.dOOdads;

namespace GrowSurv.DAL
{
	public abstract class _Answer : SqlClientEntity
	{
		public _Answer()
		{
			this.QuerySource = "Answer";
			this.MappingName = "Answer";

		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_AnswerLoadAll]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int AnswerID)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.AnswerID, AnswerID);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_AnswerLoadByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter AnswerID
			{
				get
				{
					return new SqlParameter("@AnswerID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter ArName
			{
				get
				{
					return new SqlParameter("@ArName", SqlDbType.NVarChar, 500);
				}
			}
			
			public static SqlParameter EnName
			{
				get
				{
					return new SqlParameter("@EnName", SqlDbType.NVarChar, 500);
				}
			}
			
			public static SqlParameter QuestionID
			{
				get
				{
					return new SqlParameter("@QuestionID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter NextQuestionID
			{
				get
				{
					return new SqlParameter("@NextQuestionID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter NextBranchID
			{
				get
				{
					return new SqlParameter("@NextBranchID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter Weight
			{
				get
				{
					return new SqlParameter("@Weight", SqlDbType.Decimal, 0);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string AnswerID = "AnswerID";
            public const string ArName = "ArName";
            public const string EnName = "EnName";
            public const string QuestionID = "QuestionID";
            public const string NextQuestionID = "NextQuestionID";
            public const string NextBranchID = "NextBranchID";
            public const string Weight = "Weight";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[AnswerID] = _Answer.PropertyNames.AnswerID;
					ht[ArName] = _Answer.PropertyNames.ArName;
					ht[EnName] = _Answer.PropertyNames.EnName;
					ht[QuestionID] = _Answer.PropertyNames.QuestionID;
					ht[NextQuestionID] = _Answer.PropertyNames.NextQuestionID;
					ht[NextBranchID] = _Answer.PropertyNames.NextBranchID;
					ht[Weight] = _Answer.PropertyNames.Weight;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string AnswerID = "AnswerID";
            public const string ArName = "ArName";
            public const string EnName = "EnName";
            public const string QuestionID = "QuestionID";
            public const string NextQuestionID = "NextQuestionID";
            public const string NextBranchID = "NextBranchID";
            public const string Weight = "Weight";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[AnswerID] = _Answer.ColumnNames.AnswerID;
					ht[ArName] = _Answer.ColumnNames.ArName;
					ht[EnName] = _Answer.ColumnNames.EnName;
					ht[QuestionID] = _Answer.ColumnNames.QuestionID;
					ht[NextQuestionID] = _Answer.ColumnNames.NextQuestionID;
					ht[NextBranchID] = _Answer.ColumnNames.NextBranchID;
					ht[Weight] = _Answer.ColumnNames.Weight;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string AnswerID = "s_AnswerID";
            public const string ArName = "s_ArName";
            public const string EnName = "s_EnName";
            public const string QuestionID = "s_QuestionID";
            public const string NextQuestionID = "s_NextQuestionID";
            public const string NextBranchID = "s_NextBranchID";
            public const string Weight = "s_Weight";

		}
		#endregion		
		
		#region Properties
	
		public virtual int AnswerID
	    {
			get
	        {
				return base.Getint(ColumnNames.AnswerID);
			}
			set
	        {
				base.Setint(ColumnNames.AnswerID, value);
			}
		}

		public virtual string ArName
	    {
			get
	        {
				return base.Getstring(ColumnNames.ArName);
			}
			set
	        {
				base.Setstring(ColumnNames.ArName, value);
			}
		}

		public virtual string EnName
	    {
			get
	        {
				return base.Getstring(ColumnNames.EnName);
			}
			set
	        {
				base.Setstring(ColumnNames.EnName, value);
			}
		}

		public virtual int QuestionID
	    {
			get
	        {
				return base.Getint(ColumnNames.QuestionID);
			}
			set
	        {
				base.Setint(ColumnNames.QuestionID, value);
			}
		}

		public virtual int NextQuestionID
	    {
			get
	        {
				return base.Getint(ColumnNames.NextQuestionID);
			}
			set
	        {
				base.Setint(ColumnNames.NextQuestionID, value);
			}
		}

		public virtual int NextBranchID
	    {
			get
	        {
				return base.Getint(ColumnNames.NextBranchID);
			}
			set
	        {
				base.Setint(ColumnNames.NextBranchID, value);
			}
		}

		public virtual decimal Weight
	    {
			get
	        {
				return base.Getdecimal(ColumnNames.Weight);
			}
			set
	        {
				base.Setdecimal(ColumnNames.Weight, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_AnswerID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.AnswerID) ? string.Empty : base.GetintAsString(ColumnNames.AnswerID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.AnswerID);
				else
					this.AnswerID = base.SetintAsString(ColumnNames.AnswerID, value);
			}
		}

		public virtual string s_ArName
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.ArName) ? string.Empty : base.GetstringAsString(ColumnNames.ArName);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.ArName);
				else
					this.ArName = base.SetstringAsString(ColumnNames.ArName, value);
			}
		}

		public virtual string s_EnName
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.EnName) ? string.Empty : base.GetstringAsString(ColumnNames.EnName);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.EnName);
				else
					this.EnName = base.SetstringAsString(ColumnNames.EnName, value);
			}
		}

		public virtual string s_QuestionID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.QuestionID) ? string.Empty : base.GetintAsString(ColumnNames.QuestionID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.QuestionID);
				else
					this.QuestionID = base.SetintAsString(ColumnNames.QuestionID, value);
			}
		}

		public virtual string s_NextQuestionID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.NextQuestionID) ? string.Empty : base.GetintAsString(ColumnNames.NextQuestionID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.NextQuestionID);
				else
					this.NextQuestionID = base.SetintAsString(ColumnNames.NextQuestionID, value);
			}
		}

		public virtual string s_NextBranchID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.NextBranchID) ? string.Empty : base.GetintAsString(ColumnNames.NextBranchID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.NextBranchID);
				else
					this.NextBranchID = base.SetintAsString(ColumnNames.NextBranchID, value);
			}
		}

		public virtual string s_Weight
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Weight) ? string.Empty : base.GetdecimalAsString(ColumnNames.Weight);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Weight);
				else
					this.Weight = base.SetdecimalAsString(ColumnNames.Weight, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter AnswerID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.AnswerID, Parameters.AnswerID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter ArName
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.ArName, Parameters.ArName);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter EnName
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.EnName, Parameters.EnName);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter QuestionID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.QuestionID, Parameters.QuestionID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter NextQuestionID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.NextQuestionID, Parameters.NextQuestionID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter NextBranchID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.NextBranchID, Parameters.NextBranchID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Weight
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Weight, Parameters.Weight);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter AnswerID
		    {
				get
		        {
					if(_AnswerID_W == null)
	        	    {
						_AnswerID_W = TearOff.AnswerID;
					}
					return _AnswerID_W;
				}
			}

			public WhereParameter ArName
		    {
				get
		        {
					if(_ArName_W == null)
	        	    {
						_ArName_W = TearOff.ArName;
					}
					return _ArName_W;
				}
			}

			public WhereParameter EnName
		    {
				get
		        {
					if(_EnName_W == null)
	        	    {
						_EnName_W = TearOff.EnName;
					}
					return _EnName_W;
				}
			}

			public WhereParameter QuestionID
		    {
				get
		        {
					if(_QuestionID_W == null)
	        	    {
						_QuestionID_W = TearOff.QuestionID;
					}
					return _QuestionID_W;
				}
			}

			public WhereParameter NextQuestionID
		    {
				get
		        {
					if(_NextQuestionID_W == null)
	        	    {
						_NextQuestionID_W = TearOff.NextQuestionID;
					}
					return _NextQuestionID_W;
				}
			}

			public WhereParameter NextBranchID
		    {
				get
		        {
					if(_NextBranchID_W == null)
	        	    {
						_NextBranchID_W = TearOff.NextBranchID;
					}
					return _NextBranchID_W;
				}
			}

			public WhereParameter Weight
		    {
				get
		        {
					if(_Weight_W == null)
	        	    {
						_Weight_W = TearOff.Weight;
					}
					return _Weight_W;
				}
			}

			private WhereParameter _AnswerID_W = null;
			private WhereParameter _ArName_W = null;
			private WhereParameter _EnName_W = null;
			private WhereParameter _QuestionID_W = null;
			private WhereParameter _NextQuestionID_W = null;
			private WhereParameter _NextBranchID_W = null;
			private WhereParameter _Weight_W = null;

			public void WhereClauseReset()
			{
				_AnswerID_W = null;
				_ArName_W = null;
				_EnName_W = null;
				_QuestionID_W = null;
				_NextQuestionID_W = null;
				_NextBranchID_W = null;
				_Weight_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter AnswerID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.AnswerID, Parameters.AnswerID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter ArName
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.ArName, Parameters.ArName);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter EnName
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.EnName, Parameters.EnName);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter QuestionID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.QuestionID, Parameters.QuestionID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter NextQuestionID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.NextQuestionID, Parameters.NextQuestionID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter NextBranchID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.NextBranchID, Parameters.NextBranchID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Weight
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Weight, Parameters.Weight);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter AnswerID
		    {
				get
		        {
					if(_AnswerID_W == null)
	        	    {
						_AnswerID_W = TearOff.AnswerID;
					}
					return _AnswerID_W;
				}
			}

			public AggregateParameter ArName
		    {
				get
		        {
					if(_ArName_W == null)
	        	    {
						_ArName_W = TearOff.ArName;
					}
					return _ArName_W;
				}
			}

			public AggregateParameter EnName
		    {
				get
		        {
					if(_EnName_W == null)
	        	    {
						_EnName_W = TearOff.EnName;
					}
					return _EnName_W;
				}
			}

			public AggregateParameter QuestionID
		    {
				get
		        {
					if(_QuestionID_W == null)
	        	    {
						_QuestionID_W = TearOff.QuestionID;
					}
					return _QuestionID_W;
				}
			}

			public AggregateParameter NextQuestionID
		    {
				get
		        {
					if(_NextQuestionID_W == null)
	        	    {
						_NextQuestionID_W = TearOff.NextQuestionID;
					}
					return _NextQuestionID_W;
				}
			}

			public AggregateParameter NextBranchID
		    {
				get
		        {
					if(_NextBranchID_W == null)
	        	    {
						_NextBranchID_W = TearOff.NextBranchID;
					}
					return _NextBranchID_W;
				}
			}

			public AggregateParameter Weight
		    {
				get
		        {
					if(_Weight_W == null)
	        	    {
						_Weight_W = TearOff.Weight;
					}
					return _Weight_W;
				}
			}

			private AggregateParameter _AnswerID_W = null;
			private AggregateParameter _ArName_W = null;
			private AggregateParameter _EnName_W = null;
			private AggregateParameter _QuestionID_W = null;
			private AggregateParameter _NextQuestionID_W = null;
			private AggregateParameter _NextBranchID_W = null;
			private AggregateParameter _Weight_W = null;

			public void AggregateClauseReset()
			{
				_AnswerID_W = null;
				_ArName_W = null;
				_EnName_W = null;
				_QuestionID_W = null;
				_NextQuestionID_W = null;
				_NextBranchID_W = null;
				_Weight_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_AnswerInsert]";
	
			CreateParameters(cmd);
			
			SqlParameter p;
			p = cmd.Parameters[Parameters.AnswerID.ParameterName];
			p.Direction = ParameterDirection.Output;
    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_AnswerUpdate]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_AnswerDelete]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.AnswerID);
			p.SourceColumn = ColumnNames.AnswerID;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.AnswerID);
			p.SourceColumn = ColumnNames.AnswerID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.ArName);
			p.SourceColumn = ColumnNames.ArName;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.EnName);
			p.SourceColumn = ColumnNames.EnName;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.QuestionID);
			p.SourceColumn = ColumnNames.QuestionID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.NextQuestionID);
			p.SourceColumn = ColumnNames.NextQuestionID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.NextBranchID);
			p.SourceColumn = ColumnNames.NextBranchID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Weight);
			p.SourceColumn = ColumnNames.Weight;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
