
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

using MyGeneration.dOOdads;

namespace GrowSurv.DAL
{
	public abstract class _AreaWeight : SqlClientEntity
	{
		public _AreaWeight()
		{
			this.QuerySource = "AreaWeight";
			this.MappingName = "AreaWeight";

		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_AreaWeightLoadAll]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int WeightID)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.WeightID, WeightID);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_AreaWeightLoadByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter WeightID
			{
				get
				{
					return new SqlParameter("@WeightID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter AreaID
			{
				get
				{
					return new SqlParameter("@AreaID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter SurveyID
			{
				get
				{
					return new SqlParameter("@SurveyID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter Weight
			{
				get
				{
					return new SqlParameter("@Weight", SqlDbType.Float, 0);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string WeightID = "WeightID";
            public const string AreaID = "AreaID";
            public const string SurveyID = "SurveyID";
            public const string Weight = "Weight";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[WeightID] = _AreaWeight.PropertyNames.WeightID;
					ht[AreaID] = _AreaWeight.PropertyNames.AreaID;
					ht[SurveyID] = _AreaWeight.PropertyNames.SurveyID;
					ht[Weight] = _AreaWeight.PropertyNames.Weight;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string WeightID = "WeightID";
            public const string AreaID = "AreaID";
            public const string SurveyID = "SurveyID";
            public const string Weight = "Weight";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[WeightID] = _AreaWeight.ColumnNames.WeightID;
					ht[AreaID] = _AreaWeight.ColumnNames.AreaID;
					ht[SurveyID] = _AreaWeight.ColumnNames.SurveyID;
					ht[Weight] = _AreaWeight.ColumnNames.Weight;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string WeightID = "s_WeightID";
            public const string AreaID = "s_AreaID";
            public const string SurveyID = "s_SurveyID";
            public const string Weight = "s_Weight";

		}
		#endregion		
		
		#region Properties
	
		public virtual int WeightID
	    {
			get
	        {
				return base.Getint(ColumnNames.WeightID);
			}
			set
	        {
				base.Setint(ColumnNames.WeightID, value);
			}
		}

		public virtual int AreaID
	    {
			get
	        {
				return base.Getint(ColumnNames.AreaID);
			}
			set
	        {
				base.Setint(ColumnNames.AreaID, value);
			}
		}

		public virtual int SurveyID
	    {
			get
	        {
				return base.Getint(ColumnNames.SurveyID);
			}
			set
	        {
				base.Setint(ColumnNames.SurveyID, value);
			}
		}

		public virtual double Weight
	    {
			get
	        {
				return base.Getdouble(ColumnNames.Weight);
			}
			set
	        {
				base.Setdouble(ColumnNames.Weight, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_WeightID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.WeightID) ? string.Empty : base.GetintAsString(ColumnNames.WeightID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.WeightID);
				else
					this.WeightID = base.SetintAsString(ColumnNames.WeightID, value);
			}
		}

		public virtual string s_AreaID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.AreaID) ? string.Empty : base.GetintAsString(ColumnNames.AreaID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.AreaID);
				else
					this.AreaID = base.SetintAsString(ColumnNames.AreaID, value);
			}
		}

		public virtual string s_SurveyID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.SurveyID) ? string.Empty : base.GetintAsString(ColumnNames.SurveyID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.SurveyID);
				else
					this.SurveyID = base.SetintAsString(ColumnNames.SurveyID, value);
			}
		}

		public virtual string s_Weight
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Weight) ? string.Empty : base.GetdoubleAsString(ColumnNames.Weight);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Weight);
				else
					this.Weight = base.SetdoubleAsString(ColumnNames.Weight, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter WeightID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.WeightID, Parameters.WeightID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter AreaID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.AreaID, Parameters.AreaID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter SurveyID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.SurveyID, Parameters.SurveyID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Weight
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Weight, Parameters.Weight);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter WeightID
		    {
				get
		        {
					if(_WeightID_W == null)
	        	    {
						_WeightID_W = TearOff.WeightID;
					}
					return _WeightID_W;
				}
			}

			public WhereParameter AreaID
		    {
				get
		        {
					if(_AreaID_W == null)
	        	    {
						_AreaID_W = TearOff.AreaID;
					}
					return _AreaID_W;
				}
			}

			public WhereParameter SurveyID
		    {
				get
		        {
					if(_SurveyID_W == null)
	        	    {
						_SurveyID_W = TearOff.SurveyID;
					}
					return _SurveyID_W;
				}
			}

			public WhereParameter Weight
		    {
				get
		        {
					if(_Weight_W == null)
	        	    {
						_Weight_W = TearOff.Weight;
					}
					return _Weight_W;
				}
			}

			private WhereParameter _WeightID_W = null;
			private WhereParameter _AreaID_W = null;
			private WhereParameter _SurveyID_W = null;
			private WhereParameter _Weight_W = null;

			public void WhereClauseReset()
			{
				_WeightID_W = null;
				_AreaID_W = null;
				_SurveyID_W = null;
				_Weight_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter WeightID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.WeightID, Parameters.WeightID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter AreaID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.AreaID, Parameters.AreaID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter SurveyID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.SurveyID, Parameters.SurveyID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Weight
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Weight, Parameters.Weight);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter WeightID
		    {
				get
		        {
					if(_WeightID_W == null)
	        	    {
						_WeightID_W = TearOff.WeightID;
					}
					return _WeightID_W;
				}
			}

			public AggregateParameter AreaID
		    {
				get
		        {
					if(_AreaID_W == null)
	        	    {
						_AreaID_W = TearOff.AreaID;
					}
					return _AreaID_W;
				}
			}

			public AggregateParameter SurveyID
		    {
				get
		        {
					if(_SurveyID_W == null)
	        	    {
						_SurveyID_W = TearOff.SurveyID;
					}
					return _SurveyID_W;
				}
			}

			public AggregateParameter Weight
		    {
				get
		        {
					if(_Weight_W == null)
	        	    {
						_Weight_W = TearOff.Weight;
					}
					return _Weight_W;
				}
			}

			private AggregateParameter _WeightID_W = null;
			private AggregateParameter _AreaID_W = null;
			private AggregateParameter _SurveyID_W = null;
			private AggregateParameter _Weight_W = null;

			public void AggregateClauseReset()
			{
				_WeightID_W = null;
				_AreaID_W = null;
				_SurveyID_W = null;
				_Weight_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_AreaWeightInsert]";
	
			CreateParameters(cmd);
			
			SqlParameter p;
			p = cmd.Parameters[Parameters.WeightID.ParameterName];
			p.Direction = ParameterDirection.Output;
    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_AreaWeightUpdate]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_AreaWeightDelete]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.WeightID);
			p.SourceColumn = ColumnNames.WeightID;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.WeightID);
			p.SourceColumn = ColumnNames.WeightID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.AreaID);
			p.SourceColumn = ColumnNames.AreaID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.SurveyID);
			p.SourceColumn = ColumnNames.SurveyID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Weight);
			p.SourceColumn = ColumnNames.Weight;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
