
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

using MyGeneration.dOOdads;

namespace GrowSurv.DAL
{
	public abstract class _BankQuestion : SqlClientEntity
	{
		public _BankQuestion()
		{
			this.QuerySource = "BankQuestion";
			this.MappingName = "BankQuestion";

		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_BankQuestionLoadAll]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int BankQuestionID)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.BankQuestionID, BankQuestionID);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_BankQuestionLoadByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter BankQuestionID
			{
				get
				{
					return new SqlParameter("@BankQuestionID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter BankQuestionTypeID
			{
				get
				{
					return new SqlParameter("@BankQuestionTypeID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter BankCategoryID
			{
				get
				{
					return new SqlParameter("@BankCategoryID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter ArTitle
			{
				get
				{
					return new SqlParameter("@ArTitle", SqlDbType.NVarChar, 500);
				}
			}
			
			public static SqlParameter EnTitle
			{
				get
				{
					return new SqlParameter("@EnTitle", SqlDbType.NVarChar, 500);
				}
			}
			
			public static SqlParameter IsMandatory
			{
				get
				{
					return new SqlParameter("@IsMandatory", SqlDbType.Bit, 0);
				}
			}
			
			public static SqlParameter Weight
			{
				get
				{
					return new SqlParameter("@Weight", SqlDbType.Decimal, 0);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string BankQuestionID = "BankQuestionID";
            public const string BankQuestionTypeID = "BankQuestionTypeID";
            public const string BankCategoryID = "BankCategoryID";
            public const string ArTitle = "ArTitle";
            public const string EnTitle = "EnTitle";
            public const string IsMandatory = "IsMandatory";
            public const string Weight = "Weight";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[BankQuestionID] = _BankQuestion.PropertyNames.BankQuestionID;
					ht[BankQuestionTypeID] = _BankQuestion.PropertyNames.BankQuestionTypeID;
					ht[BankCategoryID] = _BankQuestion.PropertyNames.BankCategoryID;
					ht[ArTitle] = _BankQuestion.PropertyNames.ArTitle;
					ht[EnTitle] = _BankQuestion.PropertyNames.EnTitle;
					ht[IsMandatory] = _BankQuestion.PropertyNames.IsMandatory;
					ht[Weight] = _BankQuestion.PropertyNames.Weight;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string BankQuestionID = "BankQuestionID";
            public const string BankQuestionTypeID = "BankQuestionTypeID";
            public const string BankCategoryID = "BankCategoryID";
            public const string ArTitle = "ArTitle";
            public const string EnTitle = "EnTitle";
            public const string IsMandatory = "IsMandatory";
            public const string Weight = "Weight";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[BankQuestionID] = _BankQuestion.ColumnNames.BankQuestionID;
					ht[BankQuestionTypeID] = _BankQuestion.ColumnNames.BankQuestionTypeID;
					ht[BankCategoryID] = _BankQuestion.ColumnNames.BankCategoryID;
					ht[ArTitle] = _BankQuestion.ColumnNames.ArTitle;
					ht[EnTitle] = _BankQuestion.ColumnNames.EnTitle;
					ht[IsMandatory] = _BankQuestion.ColumnNames.IsMandatory;
					ht[Weight] = _BankQuestion.ColumnNames.Weight;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string BankQuestionID = "s_BankQuestionID";
            public const string BankQuestionTypeID = "s_BankQuestionTypeID";
            public const string BankCategoryID = "s_BankCategoryID";
            public const string ArTitle = "s_ArTitle";
            public const string EnTitle = "s_EnTitle";
            public const string IsMandatory = "s_IsMandatory";
            public const string Weight = "s_Weight";

		}
		#endregion		
		
		#region Properties
	
		public virtual int BankQuestionID
	    {
			get
	        {
				return base.Getint(ColumnNames.BankQuestionID);
			}
			set
	        {
				base.Setint(ColumnNames.BankQuestionID, value);
			}
		}

		public virtual int BankQuestionTypeID
	    {
			get
	        {
				return base.Getint(ColumnNames.BankQuestionTypeID);
			}
			set
	        {
				base.Setint(ColumnNames.BankQuestionTypeID, value);
			}
		}

		public virtual int BankCategoryID
	    {
			get
	        {
				return base.Getint(ColumnNames.BankCategoryID);
			}
			set
	        {
				base.Setint(ColumnNames.BankCategoryID, value);
			}
		}

		public virtual string ArTitle
	    {
			get
	        {
				return base.Getstring(ColumnNames.ArTitle);
			}
			set
	        {
				base.Setstring(ColumnNames.ArTitle, value);
			}
		}

		public virtual string EnTitle
	    {
			get
	        {
				return base.Getstring(ColumnNames.EnTitle);
			}
			set
	        {
				base.Setstring(ColumnNames.EnTitle, value);
			}
		}

		public virtual bool IsMandatory
	    {
			get
	        {
				return base.Getbool(ColumnNames.IsMandatory);
			}
			set
	        {
				base.Setbool(ColumnNames.IsMandatory, value);
			}
		}

		public virtual decimal Weight
	    {
			get
	        {
				return base.Getdecimal(ColumnNames.Weight);
			}
			set
	        {
				base.Setdecimal(ColumnNames.Weight, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_BankQuestionID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.BankQuestionID) ? string.Empty : base.GetintAsString(ColumnNames.BankQuestionID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.BankQuestionID);
				else
					this.BankQuestionID = base.SetintAsString(ColumnNames.BankQuestionID, value);
			}
		}

		public virtual string s_BankQuestionTypeID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.BankQuestionTypeID) ? string.Empty : base.GetintAsString(ColumnNames.BankQuestionTypeID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.BankQuestionTypeID);
				else
					this.BankQuestionTypeID = base.SetintAsString(ColumnNames.BankQuestionTypeID, value);
			}
		}

		public virtual string s_BankCategoryID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.BankCategoryID) ? string.Empty : base.GetintAsString(ColumnNames.BankCategoryID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.BankCategoryID);
				else
					this.BankCategoryID = base.SetintAsString(ColumnNames.BankCategoryID, value);
			}
		}

		public virtual string s_ArTitle
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.ArTitle) ? string.Empty : base.GetstringAsString(ColumnNames.ArTitle);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.ArTitle);
				else
					this.ArTitle = base.SetstringAsString(ColumnNames.ArTitle, value);
			}
		}

		public virtual string s_EnTitle
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.EnTitle) ? string.Empty : base.GetstringAsString(ColumnNames.EnTitle);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.EnTitle);
				else
					this.EnTitle = base.SetstringAsString(ColumnNames.EnTitle, value);
			}
		}

		public virtual string s_IsMandatory
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.IsMandatory) ? string.Empty : base.GetboolAsString(ColumnNames.IsMandatory);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.IsMandatory);
				else
					this.IsMandatory = base.SetboolAsString(ColumnNames.IsMandatory, value);
			}
		}

		public virtual string s_Weight
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Weight) ? string.Empty : base.GetdecimalAsString(ColumnNames.Weight);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Weight);
				else
					this.Weight = base.SetdecimalAsString(ColumnNames.Weight, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter BankQuestionID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.BankQuestionID, Parameters.BankQuestionID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter BankQuestionTypeID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.BankQuestionTypeID, Parameters.BankQuestionTypeID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter BankCategoryID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.BankCategoryID, Parameters.BankCategoryID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter ArTitle
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.ArTitle, Parameters.ArTitle);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter EnTitle
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.EnTitle, Parameters.EnTitle);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter IsMandatory
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.IsMandatory, Parameters.IsMandatory);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Weight
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Weight, Parameters.Weight);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter BankQuestionID
		    {
				get
		        {
					if(_BankQuestionID_W == null)
	        	    {
						_BankQuestionID_W = TearOff.BankQuestionID;
					}
					return _BankQuestionID_W;
				}
			}

			public WhereParameter BankQuestionTypeID
		    {
				get
		        {
					if(_BankQuestionTypeID_W == null)
	        	    {
						_BankQuestionTypeID_W = TearOff.BankQuestionTypeID;
					}
					return _BankQuestionTypeID_W;
				}
			}

			public WhereParameter BankCategoryID
		    {
				get
		        {
					if(_BankCategoryID_W == null)
	        	    {
						_BankCategoryID_W = TearOff.BankCategoryID;
					}
					return _BankCategoryID_W;
				}
			}

			public WhereParameter ArTitle
		    {
				get
		        {
					if(_ArTitle_W == null)
	        	    {
						_ArTitle_W = TearOff.ArTitle;
					}
					return _ArTitle_W;
				}
			}

			public WhereParameter EnTitle
		    {
				get
		        {
					if(_EnTitle_W == null)
	        	    {
						_EnTitle_W = TearOff.EnTitle;
					}
					return _EnTitle_W;
				}
			}

			public WhereParameter IsMandatory
		    {
				get
		        {
					if(_IsMandatory_W == null)
	        	    {
						_IsMandatory_W = TearOff.IsMandatory;
					}
					return _IsMandatory_W;
				}
			}

			public WhereParameter Weight
		    {
				get
		        {
					if(_Weight_W == null)
	        	    {
						_Weight_W = TearOff.Weight;
					}
					return _Weight_W;
				}
			}

			private WhereParameter _BankQuestionID_W = null;
			private WhereParameter _BankQuestionTypeID_W = null;
			private WhereParameter _BankCategoryID_W = null;
			private WhereParameter _ArTitle_W = null;
			private WhereParameter _EnTitle_W = null;
			private WhereParameter _IsMandatory_W = null;
			private WhereParameter _Weight_W = null;

			public void WhereClauseReset()
			{
				_BankQuestionID_W = null;
				_BankQuestionTypeID_W = null;
				_BankCategoryID_W = null;
				_ArTitle_W = null;
				_EnTitle_W = null;
				_IsMandatory_W = null;
				_Weight_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter BankQuestionID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.BankQuestionID, Parameters.BankQuestionID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter BankQuestionTypeID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.BankQuestionTypeID, Parameters.BankQuestionTypeID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter BankCategoryID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.BankCategoryID, Parameters.BankCategoryID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter ArTitle
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.ArTitle, Parameters.ArTitle);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter EnTitle
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.EnTitle, Parameters.EnTitle);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter IsMandatory
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.IsMandatory, Parameters.IsMandatory);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Weight
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Weight, Parameters.Weight);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter BankQuestionID
		    {
				get
		        {
					if(_BankQuestionID_W == null)
	        	    {
						_BankQuestionID_W = TearOff.BankQuestionID;
					}
					return _BankQuestionID_W;
				}
			}

			public AggregateParameter BankQuestionTypeID
		    {
				get
		        {
					if(_BankQuestionTypeID_W == null)
	        	    {
						_BankQuestionTypeID_W = TearOff.BankQuestionTypeID;
					}
					return _BankQuestionTypeID_W;
				}
			}

			public AggregateParameter BankCategoryID
		    {
				get
		        {
					if(_BankCategoryID_W == null)
	        	    {
						_BankCategoryID_W = TearOff.BankCategoryID;
					}
					return _BankCategoryID_W;
				}
			}

			public AggregateParameter ArTitle
		    {
				get
		        {
					if(_ArTitle_W == null)
	        	    {
						_ArTitle_W = TearOff.ArTitle;
					}
					return _ArTitle_W;
				}
			}

			public AggregateParameter EnTitle
		    {
				get
		        {
					if(_EnTitle_W == null)
	        	    {
						_EnTitle_W = TearOff.EnTitle;
					}
					return _EnTitle_W;
				}
			}

			public AggregateParameter IsMandatory
		    {
				get
		        {
					if(_IsMandatory_W == null)
	        	    {
						_IsMandatory_W = TearOff.IsMandatory;
					}
					return _IsMandatory_W;
				}
			}

			public AggregateParameter Weight
		    {
				get
		        {
					if(_Weight_W == null)
	        	    {
						_Weight_W = TearOff.Weight;
					}
					return _Weight_W;
				}
			}

			private AggregateParameter _BankQuestionID_W = null;
			private AggregateParameter _BankQuestionTypeID_W = null;
			private AggregateParameter _BankCategoryID_W = null;
			private AggregateParameter _ArTitle_W = null;
			private AggregateParameter _EnTitle_W = null;
			private AggregateParameter _IsMandatory_W = null;
			private AggregateParameter _Weight_W = null;

			public void AggregateClauseReset()
			{
				_BankQuestionID_W = null;
				_BankQuestionTypeID_W = null;
				_BankCategoryID_W = null;
				_ArTitle_W = null;
				_EnTitle_W = null;
				_IsMandatory_W = null;
				_Weight_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_BankQuestionInsert]";
	
			CreateParameters(cmd);
			
			SqlParameter p;
			p = cmd.Parameters[Parameters.BankQuestionID.ParameterName];
			p.Direction = ParameterDirection.Output;
    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_BankQuestionUpdate]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_BankQuestionDelete]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.BankQuestionID);
			p.SourceColumn = ColumnNames.BankQuestionID;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.BankQuestionID);
			p.SourceColumn = ColumnNames.BankQuestionID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.BankQuestionTypeID);
			p.SourceColumn = ColumnNames.BankQuestionTypeID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.BankCategoryID);
			p.SourceColumn = ColumnNames.BankCategoryID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.ArTitle);
			p.SourceColumn = ColumnNames.ArTitle;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.EnTitle);
			p.SourceColumn = ColumnNames.EnTitle;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.IsMandatory);
			p.SourceColumn = ColumnNames.IsMandatory;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Weight);
			p.SourceColumn = ColumnNames.Weight;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
