
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

using MyGeneration.dOOdads;

namespace GrowSurv.DAL
{
	public abstract class _BankQuestionAnswer : SqlClientEntity
	{
		public _BankQuestionAnswer()
		{
			this.QuerySource = "BankQuestionAnswer";
			this.MappingName = "BankQuestionAnswer";

		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_BankQuestionAnswerLoadAll]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int BankQuestionAnswerID)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.BankQuestionAnswerID, BankQuestionAnswerID);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_BankQuestionAnswerLoadByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter BankQuestionAnswerID
			{
				get
				{
					return new SqlParameter("@BankQuestionAnswerID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter BankQuestionID
			{
				get
				{
					return new SqlParameter("@BankQuestionID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter ArName
			{
				get
				{
					return new SqlParameter("@ArName", SqlDbType.NVarChar, 500);
				}
			}
			
			public static SqlParameter EnName
			{
				get
				{
					return new SqlParameter("@EnName", SqlDbType.NVarChar, 500);
				}
			}
			
			public static SqlParameter Weight
			{
				get
				{
					return new SqlParameter("@Weight", SqlDbType.Decimal, 0);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string BankQuestionAnswerID = "BankQuestionAnswerID";
            public const string BankQuestionID = "BankQuestionID";
            public const string ArName = "ArName";
            public const string EnName = "EnName";
            public const string Weight = "Weight";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[BankQuestionAnswerID] = _BankQuestionAnswer.PropertyNames.BankQuestionAnswerID;
					ht[BankQuestionID] = _BankQuestionAnswer.PropertyNames.BankQuestionID;
					ht[ArName] = _BankQuestionAnswer.PropertyNames.ArName;
					ht[EnName] = _BankQuestionAnswer.PropertyNames.EnName;
					ht[Weight] = _BankQuestionAnswer.PropertyNames.Weight;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string BankQuestionAnswerID = "BankQuestionAnswerID";
            public const string BankQuestionID = "BankQuestionID";
            public const string ArName = "ArName";
            public const string EnName = "EnName";
            public const string Weight = "Weight";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[BankQuestionAnswerID] = _BankQuestionAnswer.ColumnNames.BankQuestionAnswerID;
					ht[BankQuestionID] = _BankQuestionAnswer.ColumnNames.BankQuestionID;
					ht[ArName] = _BankQuestionAnswer.ColumnNames.ArName;
					ht[EnName] = _BankQuestionAnswer.ColumnNames.EnName;
					ht[Weight] = _BankQuestionAnswer.ColumnNames.Weight;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string BankQuestionAnswerID = "s_BankQuestionAnswerID";
            public const string BankQuestionID = "s_BankQuestionID";
            public const string ArName = "s_ArName";
            public const string EnName = "s_EnName";
            public const string Weight = "s_Weight";

		}
		#endregion		
		
		#region Properties
	
		public virtual int BankQuestionAnswerID
	    {
			get
	        {
				return base.Getint(ColumnNames.BankQuestionAnswerID);
			}
			set
	        {
				base.Setint(ColumnNames.BankQuestionAnswerID, value);
			}
		}

		public virtual int BankQuestionID
	    {
			get
	        {
				return base.Getint(ColumnNames.BankQuestionID);
			}
			set
	        {
				base.Setint(ColumnNames.BankQuestionID, value);
			}
		}

		public virtual string ArName
	    {
			get
	        {
				return base.Getstring(ColumnNames.ArName);
			}
			set
	        {
				base.Setstring(ColumnNames.ArName, value);
			}
		}

		public virtual string EnName
	    {
			get
	        {
				return base.Getstring(ColumnNames.EnName);
			}
			set
	        {
				base.Setstring(ColumnNames.EnName, value);
			}
		}

		public virtual decimal Weight
	    {
			get
	        {
				return base.Getdecimal(ColumnNames.Weight);
			}
			set
	        {
				base.Setdecimal(ColumnNames.Weight, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_BankQuestionAnswerID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.BankQuestionAnswerID) ? string.Empty : base.GetintAsString(ColumnNames.BankQuestionAnswerID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.BankQuestionAnswerID);
				else
					this.BankQuestionAnswerID = base.SetintAsString(ColumnNames.BankQuestionAnswerID, value);
			}
		}

		public virtual string s_BankQuestionID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.BankQuestionID) ? string.Empty : base.GetintAsString(ColumnNames.BankQuestionID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.BankQuestionID);
				else
					this.BankQuestionID = base.SetintAsString(ColumnNames.BankQuestionID, value);
			}
		}

		public virtual string s_ArName
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.ArName) ? string.Empty : base.GetstringAsString(ColumnNames.ArName);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.ArName);
				else
					this.ArName = base.SetstringAsString(ColumnNames.ArName, value);
			}
		}

		public virtual string s_EnName
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.EnName) ? string.Empty : base.GetstringAsString(ColumnNames.EnName);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.EnName);
				else
					this.EnName = base.SetstringAsString(ColumnNames.EnName, value);
			}
		}

		public virtual string s_Weight
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Weight) ? string.Empty : base.GetdecimalAsString(ColumnNames.Weight);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Weight);
				else
					this.Weight = base.SetdecimalAsString(ColumnNames.Weight, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter BankQuestionAnswerID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.BankQuestionAnswerID, Parameters.BankQuestionAnswerID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter BankQuestionID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.BankQuestionID, Parameters.BankQuestionID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter ArName
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.ArName, Parameters.ArName);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter EnName
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.EnName, Parameters.EnName);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Weight
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Weight, Parameters.Weight);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter BankQuestionAnswerID
		    {
				get
		        {
					if(_BankQuestionAnswerID_W == null)
	        	    {
						_BankQuestionAnswerID_W = TearOff.BankQuestionAnswerID;
					}
					return _BankQuestionAnswerID_W;
				}
			}

			public WhereParameter BankQuestionID
		    {
				get
		        {
					if(_BankQuestionID_W == null)
	        	    {
						_BankQuestionID_W = TearOff.BankQuestionID;
					}
					return _BankQuestionID_W;
				}
			}

			public WhereParameter ArName
		    {
				get
		        {
					if(_ArName_W == null)
	        	    {
						_ArName_W = TearOff.ArName;
					}
					return _ArName_W;
				}
			}

			public WhereParameter EnName
		    {
				get
		        {
					if(_EnName_W == null)
	        	    {
						_EnName_W = TearOff.EnName;
					}
					return _EnName_W;
				}
			}

			public WhereParameter Weight
		    {
				get
		        {
					if(_Weight_W == null)
	        	    {
						_Weight_W = TearOff.Weight;
					}
					return _Weight_W;
				}
			}

			private WhereParameter _BankQuestionAnswerID_W = null;
			private WhereParameter _BankQuestionID_W = null;
			private WhereParameter _ArName_W = null;
			private WhereParameter _EnName_W = null;
			private WhereParameter _Weight_W = null;

			public void WhereClauseReset()
			{
				_BankQuestionAnswerID_W = null;
				_BankQuestionID_W = null;
				_ArName_W = null;
				_EnName_W = null;
				_Weight_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter BankQuestionAnswerID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.BankQuestionAnswerID, Parameters.BankQuestionAnswerID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter BankQuestionID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.BankQuestionID, Parameters.BankQuestionID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter ArName
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.ArName, Parameters.ArName);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter EnName
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.EnName, Parameters.EnName);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Weight
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Weight, Parameters.Weight);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter BankQuestionAnswerID
		    {
				get
		        {
					if(_BankQuestionAnswerID_W == null)
	        	    {
						_BankQuestionAnswerID_W = TearOff.BankQuestionAnswerID;
					}
					return _BankQuestionAnswerID_W;
				}
			}

			public AggregateParameter BankQuestionID
		    {
				get
		        {
					if(_BankQuestionID_W == null)
	        	    {
						_BankQuestionID_W = TearOff.BankQuestionID;
					}
					return _BankQuestionID_W;
				}
			}

			public AggregateParameter ArName
		    {
				get
		        {
					if(_ArName_W == null)
	        	    {
						_ArName_W = TearOff.ArName;
					}
					return _ArName_W;
				}
			}

			public AggregateParameter EnName
		    {
				get
		        {
					if(_EnName_W == null)
	        	    {
						_EnName_W = TearOff.EnName;
					}
					return _EnName_W;
				}
			}

			public AggregateParameter Weight
		    {
				get
		        {
					if(_Weight_W == null)
	        	    {
						_Weight_W = TearOff.Weight;
					}
					return _Weight_W;
				}
			}

			private AggregateParameter _BankQuestionAnswerID_W = null;
			private AggregateParameter _BankQuestionID_W = null;
			private AggregateParameter _ArName_W = null;
			private AggregateParameter _EnName_W = null;
			private AggregateParameter _Weight_W = null;

			public void AggregateClauseReset()
			{
				_BankQuestionAnswerID_W = null;
				_BankQuestionID_W = null;
				_ArName_W = null;
				_EnName_W = null;
				_Weight_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_BankQuestionAnswerInsert]";
	
			CreateParameters(cmd);
			
			SqlParameter p;
			p = cmd.Parameters[Parameters.BankQuestionAnswerID.ParameterName];
			p.Direction = ParameterDirection.Output;
    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_BankQuestionAnswerUpdate]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_BankQuestionAnswerDelete]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.BankQuestionAnswerID);
			p.SourceColumn = ColumnNames.BankQuestionAnswerID;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.BankQuestionAnswerID);
			p.SourceColumn = ColumnNames.BankQuestionAnswerID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.BankQuestionID);
			p.SourceColumn = ColumnNames.BankQuestionID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.ArName);
			p.SourceColumn = ColumnNames.ArName;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.EnName);
			p.SourceColumn = ColumnNames.EnName;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Weight);
			p.SourceColumn = ColumnNames.Weight;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
