
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

using MyGeneration.dOOdads;

namespace GrowSurv.DAL
{
	public abstract class _Gender : SqlClientEntity
	{
		public _Gender()
		{
			this.QuerySource = "Gender";
			this.MappingName = "Gender";

		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_GenderLoadAll]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int GenderID)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.GenderID, GenderID);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_GenderLoadByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter GenderID
			{
				get
				{
					return new SqlParameter("@GenderID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter NameEn
			{
				get
				{
					return new SqlParameter("@NameEn", SqlDbType.NVarChar, 500);
				}
			}
			
			public static SqlParameter NameAr
			{
				get
				{
					return new SqlParameter("@NameAr", SqlDbType.NVarChar, 500);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string GenderID = "GenderID";
            public const string NameEn = "NameEn";
            public const string NameAr = "NameAr";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[GenderID] = _Gender.PropertyNames.GenderID;
					ht[NameEn] = _Gender.PropertyNames.NameEn;
					ht[NameAr] = _Gender.PropertyNames.NameAr;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string GenderID = "GenderID";
            public const string NameEn = "NameEn";
            public const string NameAr = "NameAr";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[GenderID] = _Gender.ColumnNames.GenderID;
					ht[NameEn] = _Gender.ColumnNames.NameEn;
					ht[NameAr] = _Gender.ColumnNames.NameAr;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string GenderID = "s_GenderID";
            public const string NameEn = "s_NameEn";
            public const string NameAr = "s_NameAr";

		}
		#endregion		
		
		#region Properties
	
		public virtual int GenderID
	    {
			get
	        {
				return base.Getint(ColumnNames.GenderID);
			}
			set
	        {
				base.Setint(ColumnNames.GenderID, value);
			}
		}

		public virtual string NameEn
	    {
			get
	        {
				return base.Getstring(ColumnNames.NameEn);
			}
			set
	        {
				base.Setstring(ColumnNames.NameEn, value);
			}
		}

		public virtual string NameAr
	    {
			get
	        {
				return base.Getstring(ColumnNames.NameAr);
			}
			set
	        {
				base.Setstring(ColumnNames.NameAr, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_GenderID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.GenderID) ? string.Empty : base.GetintAsString(ColumnNames.GenderID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.GenderID);
				else
					this.GenderID = base.SetintAsString(ColumnNames.GenderID, value);
			}
		}

		public virtual string s_NameEn
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.NameEn) ? string.Empty : base.GetstringAsString(ColumnNames.NameEn);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.NameEn);
				else
					this.NameEn = base.SetstringAsString(ColumnNames.NameEn, value);
			}
		}

		public virtual string s_NameAr
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.NameAr) ? string.Empty : base.GetstringAsString(ColumnNames.NameAr);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.NameAr);
				else
					this.NameAr = base.SetstringAsString(ColumnNames.NameAr, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter GenderID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.GenderID, Parameters.GenderID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter NameEn
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.NameEn, Parameters.NameEn);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter NameAr
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.NameAr, Parameters.NameAr);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter GenderID
		    {
				get
		        {
					if(_GenderID_W == null)
	        	    {
						_GenderID_W = TearOff.GenderID;
					}
					return _GenderID_W;
				}
			}

			public WhereParameter NameEn
		    {
				get
		        {
					if(_NameEn_W == null)
	        	    {
						_NameEn_W = TearOff.NameEn;
					}
					return _NameEn_W;
				}
			}

			public WhereParameter NameAr
		    {
				get
		        {
					if(_NameAr_W == null)
	        	    {
						_NameAr_W = TearOff.NameAr;
					}
					return _NameAr_W;
				}
			}

			private WhereParameter _GenderID_W = null;
			private WhereParameter _NameEn_W = null;
			private WhereParameter _NameAr_W = null;

			public void WhereClauseReset()
			{
				_GenderID_W = null;
				_NameEn_W = null;
				_NameAr_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter GenderID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.GenderID, Parameters.GenderID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter NameEn
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.NameEn, Parameters.NameEn);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter NameAr
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.NameAr, Parameters.NameAr);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter GenderID
		    {
				get
		        {
					if(_GenderID_W == null)
	        	    {
						_GenderID_W = TearOff.GenderID;
					}
					return _GenderID_W;
				}
			}

			public AggregateParameter NameEn
		    {
				get
		        {
					if(_NameEn_W == null)
	        	    {
						_NameEn_W = TearOff.NameEn;
					}
					return _NameEn_W;
				}
			}

			public AggregateParameter NameAr
		    {
				get
		        {
					if(_NameAr_W == null)
	        	    {
						_NameAr_W = TearOff.NameAr;
					}
					return _NameAr_W;
				}
			}

			private AggregateParameter _GenderID_W = null;
			private AggregateParameter _NameEn_W = null;
			private AggregateParameter _NameAr_W = null;

			public void AggregateClauseReset()
			{
				_GenderID_W = null;
				_NameEn_W = null;
				_NameAr_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_GenderInsert]";
	
			CreateParameters(cmd);
			
			SqlParameter p;
			p = cmd.Parameters[Parameters.GenderID.ParameterName];
			p.Direction = ParameterDirection.Output;
    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_GenderUpdate]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_GenderDelete]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.GenderID);
			p.SourceColumn = ColumnNames.GenderID;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.GenderID);
			p.SourceColumn = ColumnNames.GenderID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.NameEn);
			p.SourceColumn = ColumnNames.NameEn;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.NameAr);
			p.SourceColumn = ColumnNames.NameAr;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
