
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

using MyGeneration.dOOdads;

namespace GrowSurv.DAL
{
	public abstract class _Governrate : SqlClientEntity
	{
		public _Governrate()
		{
			this.QuerySource = "Governrate";
			this.MappingName = "Governrate";

		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_GovernrateLoadAll]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int GovernrateID)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.GovernrateID, GovernrateID);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_GovernrateLoadByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter GovernrateID
			{
				get
				{
					return new SqlParameter("@GovernrateID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter ArName
			{
				get
				{
					return new SqlParameter("@ArName", SqlDbType.NVarChar, 150);
				}
			}
			
			public static SqlParameter EnName
			{
				get
				{
					return new SqlParameter("@EnName", SqlDbType.NVarChar, 150);
				}
			}
			
			public static SqlParameter CompanyID
			{
				get
				{
					return new SqlParameter("@CompanyID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter IsActive
			{
				get
				{
					return new SqlParameter("@IsActive", SqlDbType.Bit, 0);
				}
			}
			
			public static SqlParameter CountryID
			{
				get
				{
					return new SqlParameter("@CountryID", SqlDbType.Int, 0);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string GovernrateID = "GovernrateID";
            public const string ArName = "ArName";
            public const string EnName = "EnName";
            public const string CompanyID = "CompanyID";
            public const string IsActive = "IsActive";
            public const string CountryID = "CountryID";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[GovernrateID] = _Governrate.PropertyNames.GovernrateID;
					ht[ArName] = _Governrate.PropertyNames.ArName;
					ht[EnName] = _Governrate.PropertyNames.EnName;
					ht[CompanyID] = _Governrate.PropertyNames.CompanyID;
					ht[IsActive] = _Governrate.PropertyNames.IsActive;
					ht[CountryID] = _Governrate.PropertyNames.CountryID;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string GovernrateID = "GovernrateID";
            public const string ArName = "ArName";
            public const string EnName = "EnName";
            public const string CompanyID = "CompanyID";
            public const string IsActive = "IsActive";
            public const string CountryID = "CountryID";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[GovernrateID] = _Governrate.ColumnNames.GovernrateID;
					ht[ArName] = _Governrate.ColumnNames.ArName;
					ht[EnName] = _Governrate.ColumnNames.EnName;
					ht[CompanyID] = _Governrate.ColumnNames.CompanyID;
					ht[IsActive] = _Governrate.ColumnNames.IsActive;
					ht[CountryID] = _Governrate.ColumnNames.CountryID;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string GovernrateID = "s_GovernrateID";
            public const string ArName = "s_ArName";
            public const string EnName = "s_EnName";
            public const string CompanyID = "s_CompanyID";
            public const string IsActive = "s_IsActive";
            public const string CountryID = "s_CountryID";

		}
		#endregion		
		
		#region Properties
	
		public virtual int GovernrateID
	    {
			get
	        {
				return base.Getint(ColumnNames.GovernrateID);
			}
			set
	        {
				base.Setint(ColumnNames.GovernrateID, value);
			}
		}

		public virtual string ArName
	    {
			get
	        {
				return base.Getstring(ColumnNames.ArName);
			}
			set
	        {
				base.Setstring(ColumnNames.ArName, value);
			}
		}

		public virtual string EnName
	    {
			get
	        {
				return base.Getstring(ColumnNames.EnName);
			}
			set
	        {
				base.Setstring(ColumnNames.EnName, value);
			}
		}

		public virtual int CompanyID
	    {
			get
	        {
				return base.Getint(ColumnNames.CompanyID);
			}
			set
	        {
				base.Setint(ColumnNames.CompanyID, value);
			}
		}

		public virtual bool IsActive
	    {
			get
	        {
				return base.Getbool(ColumnNames.IsActive);
			}
			set
	        {
				base.Setbool(ColumnNames.IsActive, value);
			}
		}

		public virtual int CountryID
	    {
			get
	        {
				return base.Getint(ColumnNames.CountryID);
			}
			set
	        {
				base.Setint(ColumnNames.CountryID, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_GovernrateID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.GovernrateID) ? string.Empty : base.GetintAsString(ColumnNames.GovernrateID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.GovernrateID);
				else
					this.GovernrateID = base.SetintAsString(ColumnNames.GovernrateID, value);
			}
		}

		public virtual string s_ArName
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.ArName) ? string.Empty : base.GetstringAsString(ColumnNames.ArName);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.ArName);
				else
					this.ArName = base.SetstringAsString(ColumnNames.ArName, value);
			}
		}

		public virtual string s_EnName
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.EnName) ? string.Empty : base.GetstringAsString(ColumnNames.EnName);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.EnName);
				else
					this.EnName = base.SetstringAsString(ColumnNames.EnName, value);
			}
		}

		public virtual string s_CompanyID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.CompanyID) ? string.Empty : base.GetintAsString(ColumnNames.CompanyID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.CompanyID);
				else
					this.CompanyID = base.SetintAsString(ColumnNames.CompanyID, value);
			}
		}

		public virtual string s_IsActive
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.IsActive) ? string.Empty : base.GetboolAsString(ColumnNames.IsActive);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.IsActive);
				else
					this.IsActive = base.SetboolAsString(ColumnNames.IsActive, value);
			}
		}

		public virtual string s_CountryID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.CountryID) ? string.Empty : base.GetintAsString(ColumnNames.CountryID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.CountryID);
				else
					this.CountryID = base.SetintAsString(ColumnNames.CountryID, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter GovernrateID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.GovernrateID, Parameters.GovernrateID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter ArName
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.ArName, Parameters.ArName);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter EnName
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.EnName, Parameters.EnName);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter CompanyID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.CompanyID, Parameters.CompanyID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter IsActive
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.IsActive, Parameters.IsActive);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter CountryID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.CountryID, Parameters.CountryID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter GovernrateID
		    {
				get
		        {
					if(_GovernrateID_W == null)
	        	    {
						_GovernrateID_W = TearOff.GovernrateID;
					}
					return _GovernrateID_W;
				}
			}

			public WhereParameter ArName
		    {
				get
		        {
					if(_ArName_W == null)
	        	    {
						_ArName_W = TearOff.ArName;
					}
					return _ArName_W;
				}
			}

			public WhereParameter EnName
		    {
				get
		        {
					if(_EnName_W == null)
	        	    {
						_EnName_W = TearOff.EnName;
					}
					return _EnName_W;
				}
			}

			public WhereParameter CompanyID
		    {
				get
		        {
					if(_CompanyID_W == null)
	        	    {
						_CompanyID_W = TearOff.CompanyID;
					}
					return _CompanyID_W;
				}
			}

			public WhereParameter IsActive
		    {
				get
		        {
					if(_IsActive_W == null)
	        	    {
						_IsActive_W = TearOff.IsActive;
					}
					return _IsActive_W;
				}
			}

			public WhereParameter CountryID
		    {
				get
		        {
					if(_CountryID_W == null)
	        	    {
						_CountryID_W = TearOff.CountryID;
					}
					return _CountryID_W;
				}
			}

			private WhereParameter _GovernrateID_W = null;
			private WhereParameter _ArName_W = null;
			private WhereParameter _EnName_W = null;
			private WhereParameter _CompanyID_W = null;
			private WhereParameter _IsActive_W = null;
			private WhereParameter _CountryID_W = null;

			public void WhereClauseReset()
			{
				_GovernrateID_W = null;
				_ArName_W = null;
				_EnName_W = null;
				_CompanyID_W = null;
				_IsActive_W = null;
				_CountryID_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter GovernrateID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.GovernrateID, Parameters.GovernrateID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter ArName
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.ArName, Parameters.ArName);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter EnName
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.EnName, Parameters.EnName);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter CompanyID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.CompanyID, Parameters.CompanyID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter IsActive
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.IsActive, Parameters.IsActive);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter CountryID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.CountryID, Parameters.CountryID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter GovernrateID
		    {
				get
		        {
					if(_GovernrateID_W == null)
	        	    {
						_GovernrateID_W = TearOff.GovernrateID;
					}
					return _GovernrateID_W;
				}
			}

			public AggregateParameter ArName
		    {
				get
		        {
					if(_ArName_W == null)
	        	    {
						_ArName_W = TearOff.ArName;
					}
					return _ArName_W;
				}
			}

			public AggregateParameter EnName
		    {
				get
		        {
					if(_EnName_W == null)
	        	    {
						_EnName_W = TearOff.EnName;
					}
					return _EnName_W;
				}
			}

			public AggregateParameter CompanyID
		    {
				get
		        {
					if(_CompanyID_W == null)
	        	    {
						_CompanyID_W = TearOff.CompanyID;
					}
					return _CompanyID_W;
				}
			}

			public AggregateParameter IsActive
		    {
				get
		        {
					if(_IsActive_W == null)
	        	    {
						_IsActive_W = TearOff.IsActive;
					}
					return _IsActive_W;
				}
			}

			public AggregateParameter CountryID
		    {
				get
		        {
					if(_CountryID_W == null)
	        	    {
						_CountryID_W = TearOff.CountryID;
					}
					return _CountryID_W;
				}
			}

			private AggregateParameter _GovernrateID_W = null;
			private AggregateParameter _ArName_W = null;
			private AggregateParameter _EnName_W = null;
			private AggregateParameter _CompanyID_W = null;
			private AggregateParameter _IsActive_W = null;
			private AggregateParameter _CountryID_W = null;

			public void AggregateClauseReset()
			{
				_GovernrateID_W = null;
				_ArName_W = null;
				_EnName_W = null;
				_CompanyID_W = null;
				_IsActive_W = null;
				_CountryID_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_GovernrateInsert]";
	
			CreateParameters(cmd);
			
			SqlParameter p;
			p = cmd.Parameters[Parameters.GovernrateID.ParameterName];
			p.Direction = ParameterDirection.Output;
    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_GovernrateUpdate]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_GovernrateDelete]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.GovernrateID);
			p.SourceColumn = ColumnNames.GovernrateID;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.GovernrateID);
			p.SourceColumn = ColumnNames.GovernrateID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.ArName);
			p.SourceColumn = ColumnNames.ArName;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.EnName);
			p.SourceColumn = ColumnNames.EnName;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.CompanyID);
			p.SourceColumn = ColumnNames.CompanyID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.IsActive);
			p.SourceColumn = ColumnNames.IsActive;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.CountryID);
			p.SourceColumn = ColumnNames.CountryID;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
