
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

using MyGeneration.dOOdads;

namespace GrowSurv.DAL
{
	public abstract class _SurveyDepartment : SqlClientEntity
	{
		public _SurveyDepartment()
		{
			this.QuerySource = "SurveyDepartment";
			this.MappingName = "SurveyDepartment";

		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_SurveyDepartmentLoadAll]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int SurveyDepartmentID)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.SurveyDepartmentID, SurveyDepartmentID);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_SurveyDepartmentLoadByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter SurveyDepartmentID
			{
				get
				{
					return new SqlParameter("@SurveyDepartmentID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter SurveyID
			{
				get
				{
					return new SqlParameter("@SurveyID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter DepartmentID
			{
				get
				{
					return new SqlParameter("@DepartmentID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter Weight
			{
				get
				{
					return new SqlParameter("@Weight", SqlDbType.Decimal, 0);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string SurveyDepartmentID = "SurveyDepartmentID";
            public const string SurveyID = "SurveyID";
            public const string DepartmentID = "DepartmentID";
            public const string Weight = "Weight";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[SurveyDepartmentID] = _SurveyDepartment.PropertyNames.SurveyDepartmentID;
					ht[SurveyID] = _SurveyDepartment.PropertyNames.SurveyID;
					ht[DepartmentID] = _SurveyDepartment.PropertyNames.DepartmentID;
					ht[Weight] = _SurveyDepartment.PropertyNames.Weight;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string SurveyDepartmentID = "SurveyDepartmentID";
            public const string SurveyID = "SurveyID";
            public const string DepartmentID = "DepartmentID";
            public const string Weight = "Weight";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[SurveyDepartmentID] = _SurveyDepartment.ColumnNames.SurveyDepartmentID;
					ht[SurveyID] = _SurveyDepartment.ColumnNames.SurveyID;
					ht[DepartmentID] = _SurveyDepartment.ColumnNames.DepartmentID;
					ht[Weight] = _SurveyDepartment.ColumnNames.Weight;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string SurveyDepartmentID = "s_SurveyDepartmentID";
            public const string SurveyID = "s_SurveyID";
            public const string DepartmentID = "s_DepartmentID";
            public const string Weight = "s_Weight";

		}
		#endregion		
		
		#region Properties
	
		public virtual int SurveyDepartmentID
	    {
			get
	        {
				return base.Getint(ColumnNames.SurveyDepartmentID);
			}
			set
	        {
				base.Setint(ColumnNames.SurveyDepartmentID, value);
			}
		}

		public virtual int SurveyID
	    {
			get
	        {
				return base.Getint(ColumnNames.SurveyID);
			}
			set
	        {
				base.Setint(ColumnNames.SurveyID, value);
			}
		}

		public virtual int DepartmentID
	    {
			get
	        {
				return base.Getint(ColumnNames.DepartmentID);
			}
			set
	        {
				base.Setint(ColumnNames.DepartmentID, value);
			}
		}

		public virtual decimal Weight
	    {
			get
	        {
				return base.Getdecimal(ColumnNames.Weight);
			}
			set
	        {
				base.Setdecimal(ColumnNames.Weight, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_SurveyDepartmentID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.SurveyDepartmentID) ? string.Empty : base.GetintAsString(ColumnNames.SurveyDepartmentID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.SurveyDepartmentID);
				else
					this.SurveyDepartmentID = base.SetintAsString(ColumnNames.SurveyDepartmentID, value);
			}
		}

		public virtual string s_SurveyID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.SurveyID) ? string.Empty : base.GetintAsString(ColumnNames.SurveyID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.SurveyID);
				else
					this.SurveyID = base.SetintAsString(ColumnNames.SurveyID, value);
			}
		}

		public virtual string s_DepartmentID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.DepartmentID) ? string.Empty : base.GetintAsString(ColumnNames.DepartmentID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.DepartmentID);
				else
					this.DepartmentID = base.SetintAsString(ColumnNames.DepartmentID, value);
			}
		}

		public virtual string s_Weight
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Weight) ? string.Empty : base.GetdecimalAsString(ColumnNames.Weight);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Weight);
				else
					this.Weight = base.SetdecimalAsString(ColumnNames.Weight, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter SurveyDepartmentID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.SurveyDepartmentID, Parameters.SurveyDepartmentID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter SurveyID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.SurveyID, Parameters.SurveyID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter DepartmentID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.DepartmentID, Parameters.DepartmentID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Weight
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Weight, Parameters.Weight);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter SurveyDepartmentID
		    {
				get
		        {
					if(_SurveyDepartmentID_W == null)
	        	    {
						_SurveyDepartmentID_W = TearOff.SurveyDepartmentID;
					}
					return _SurveyDepartmentID_W;
				}
			}

			public WhereParameter SurveyID
		    {
				get
		        {
					if(_SurveyID_W == null)
	        	    {
						_SurveyID_W = TearOff.SurveyID;
					}
					return _SurveyID_W;
				}
			}

			public WhereParameter DepartmentID
		    {
				get
		        {
					if(_DepartmentID_W == null)
	        	    {
						_DepartmentID_W = TearOff.DepartmentID;
					}
					return _DepartmentID_W;
				}
			}

			public WhereParameter Weight
		    {
				get
		        {
					if(_Weight_W == null)
	        	    {
						_Weight_W = TearOff.Weight;
					}
					return _Weight_W;
				}
			}

			private WhereParameter _SurveyDepartmentID_W = null;
			private WhereParameter _SurveyID_W = null;
			private WhereParameter _DepartmentID_W = null;
			private WhereParameter _Weight_W = null;

			public void WhereClauseReset()
			{
				_SurveyDepartmentID_W = null;
				_SurveyID_W = null;
				_DepartmentID_W = null;
				_Weight_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter SurveyDepartmentID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.SurveyDepartmentID, Parameters.SurveyDepartmentID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter SurveyID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.SurveyID, Parameters.SurveyID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter DepartmentID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.DepartmentID, Parameters.DepartmentID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Weight
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Weight, Parameters.Weight);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter SurveyDepartmentID
		    {
				get
		        {
					if(_SurveyDepartmentID_W == null)
	        	    {
						_SurveyDepartmentID_W = TearOff.SurveyDepartmentID;
					}
					return _SurveyDepartmentID_W;
				}
			}

			public AggregateParameter SurveyID
		    {
				get
		        {
					if(_SurveyID_W == null)
	        	    {
						_SurveyID_W = TearOff.SurveyID;
					}
					return _SurveyID_W;
				}
			}

			public AggregateParameter DepartmentID
		    {
				get
		        {
					if(_DepartmentID_W == null)
	        	    {
						_DepartmentID_W = TearOff.DepartmentID;
					}
					return _DepartmentID_W;
				}
			}

			public AggregateParameter Weight
		    {
				get
		        {
					if(_Weight_W == null)
	        	    {
						_Weight_W = TearOff.Weight;
					}
					return _Weight_W;
				}
			}

			private AggregateParameter _SurveyDepartmentID_W = null;
			private AggregateParameter _SurveyID_W = null;
			private AggregateParameter _DepartmentID_W = null;
			private AggregateParameter _Weight_W = null;

			public void AggregateClauseReset()
			{
				_SurveyDepartmentID_W = null;
				_SurveyID_W = null;
				_DepartmentID_W = null;
				_Weight_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_SurveyDepartmentInsert]";
	
			CreateParameters(cmd);
			    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_SurveyDepartmentUpdate]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_SurveyDepartmentDelete]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.SurveyDepartmentID);
			p.SourceColumn = ColumnNames.SurveyDepartmentID;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.SurveyDepartmentID);
			p.SourceColumn = ColumnNames.SurveyDepartmentID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.SurveyID);
			p.SourceColumn = ColumnNames.SurveyID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.DepartmentID);
			p.SourceColumn = ColumnNames.DepartmentID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Weight);
			p.SourceColumn = ColumnNames.Weight;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
