
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

using MyGeneration.dOOdads;

namespace GrowSurv.DAL
{
	public abstract class _SurveyMemberAnswer : SqlClientEntity
	{
		public _SurveyMemberAnswer()
		{
			this.QuerySource = "SurveyMemberAnswer";
			this.MappingName = "SurveyMemberAnswer";

		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_SurveyMemberAnswerLoadAll]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int SurveyMemberAnwerID)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.SurveyMemberAnwerID, SurveyMemberAnwerID);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_SurveyMemberAnswerLoadByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter SurveyMemberAnwerID
			{
				get
				{
					return new SqlParameter("@SurveyMemberAnwerID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter SurveyMemberID
			{
				get
				{
					return new SqlParameter("@SurveyMemberID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter AnswerID
			{
				get
				{
					return new SqlParameter("@AnswerID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter QuestionID
			{
				get
				{
					return new SqlParameter("@QuestionID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter AnswerText
			{
				get
				{
					return new SqlParameter("@AnswerText", SqlDbType.NVarChar, 1073741823);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string SurveyMemberAnwerID = "SurveyMemberAnwerID";
            public const string SurveyMemberID = "SurveyMemberID";
            public const string AnswerID = "AnswerID";
            public const string QuestionID = "QuestionID";
            public const string AnswerText = "AnswerText";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[SurveyMemberAnwerID] = _SurveyMemberAnswer.PropertyNames.SurveyMemberAnwerID;
					ht[SurveyMemberID] = _SurveyMemberAnswer.PropertyNames.SurveyMemberID;
					ht[AnswerID] = _SurveyMemberAnswer.PropertyNames.AnswerID;
					ht[QuestionID] = _SurveyMemberAnswer.PropertyNames.QuestionID;
					ht[AnswerText] = _SurveyMemberAnswer.PropertyNames.AnswerText;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string SurveyMemberAnwerID = "SurveyMemberAnwerID";
            public const string SurveyMemberID = "SurveyMemberID";
            public const string AnswerID = "AnswerID";
            public const string QuestionID = "QuestionID";
            public const string AnswerText = "AnswerText";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[SurveyMemberAnwerID] = _SurveyMemberAnswer.ColumnNames.SurveyMemberAnwerID;
					ht[SurveyMemberID] = _SurveyMemberAnswer.ColumnNames.SurveyMemberID;
					ht[AnswerID] = _SurveyMemberAnswer.ColumnNames.AnswerID;
					ht[QuestionID] = _SurveyMemberAnswer.ColumnNames.QuestionID;
					ht[AnswerText] = _SurveyMemberAnswer.ColumnNames.AnswerText;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string SurveyMemberAnwerID = "s_SurveyMemberAnwerID";
            public const string SurveyMemberID = "s_SurveyMemberID";
            public const string AnswerID = "s_AnswerID";
            public const string QuestionID = "s_QuestionID";
            public const string AnswerText = "s_AnswerText";

		}
		#endregion		
		
		#region Properties
	
		public virtual int SurveyMemberAnwerID
	    {
			get
	        {
				return base.Getint(ColumnNames.SurveyMemberAnwerID);
			}
			set
	        {
				base.Setint(ColumnNames.SurveyMemberAnwerID, value);
			}
		}

		public virtual int SurveyMemberID
	    {
			get
	        {
				return base.Getint(ColumnNames.SurveyMemberID);
			}
			set
	        {
				base.Setint(ColumnNames.SurveyMemberID, value);
			}
		}

		public virtual int AnswerID
	    {
			get
	        {
				return base.Getint(ColumnNames.AnswerID);
			}
			set
	        {
				base.Setint(ColumnNames.AnswerID, value);
			}
		}

		public virtual int QuestionID
	    {
			get
	        {
				return base.Getint(ColumnNames.QuestionID);
			}
			set
	        {
				base.Setint(ColumnNames.QuestionID, value);
			}
		}

		public virtual string AnswerText
	    {
			get
	        {
				return base.Getstring(ColumnNames.AnswerText);
			}
			set
	        {
				base.Setstring(ColumnNames.AnswerText, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_SurveyMemberAnwerID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.SurveyMemberAnwerID) ? string.Empty : base.GetintAsString(ColumnNames.SurveyMemberAnwerID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.SurveyMemberAnwerID);
				else
					this.SurveyMemberAnwerID = base.SetintAsString(ColumnNames.SurveyMemberAnwerID, value);
			}
		}

		public virtual string s_SurveyMemberID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.SurveyMemberID) ? string.Empty : base.GetintAsString(ColumnNames.SurveyMemberID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.SurveyMemberID);
				else
					this.SurveyMemberID = base.SetintAsString(ColumnNames.SurveyMemberID, value);
			}
		}

		public virtual string s_AnswerID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.AnswerID) ? string.Empty : base.GetintAsString(ColumnNames.AnswerID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.AnswerID);
				else
					this.AnswerID = base.SetintAsString(ColumnNames.AnswerID, value);
			}
		}

		public virtual string s_QuestionID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.QuestionID) ? string.Empty : base.GetintAsString(ColumnNames.QuestionID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.QuestionID);
				else
					this.QuestionID = base.SetintAsString(ColumnNames.QuestionID, value);
			}
		}

		public virtual string s_AnswerText
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.AnswerText) ? string.Empty : base.GetstringAsString(ColumnNames.AnswerText);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.AnswerText);
				else
					this.AnswerText = base.SetstringAsString(ColumnNames.AnswerText, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter SurveyMemberAnwerID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.SurveyMemberAnwerID, Parameters.SurveyMemberAnwerID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter SurveyMemberID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.SurveyMemberID, Parameters.SurveyMemberID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter AnswerID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.AnswerID, Parameters.AnswerID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter QuestionID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.QuestionID, Parameters.QuestionID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter AnswerText
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.AnswerText, Parameters.AnswerText);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter SurveyMemberAnwerID
		    {
				get
		        {
					if(_SurveyMemberAnwerID_W == null)
	        	    {
						_SurveyMemberAnwerID_W = TearOff.SurveyMemberAnwerID;
					}
					return _SurveyMemberAnwerID_W;
				}
			}

			public WhereParameter SurveyMemberID
		    {
				get
		        {
					if(_SurveyMemberID_W == null)
	        	    {
						_SurveyMemberID_W = TearOff.SurveyMemberID;
					}
					return _SurveyMemberID_W;
				}
			}

			public WhereParameter AnswerID
		    {
				get
		        {
					if(_AnswerID_W == null)
	        	    {
						_AnswerID_W = TearOff.AnswerID;
					}
					return _AnswerID_W;
				}
			}

			public WhereParameter QuestionID
		    {
				get
		        {
					if(_QuestionID_W == null)
	        	    {
						_QuestionID_W = TearOff.QuestionID;
					}
					return _QuestionID_W;
				}
			}

			public WhereParameter AnswerText
		    {
				get
		        {
					if(_AnswerText_W == null)
	        	    {
						_AnswerText_W = TearOff.AnswerText;
					}
					return _AnswerText_W;
				}
			}

			private WhereParameter _SurveyMemberAnwerID_W = null;
			private WhereParameter _SurveyMemberID_W = null;
			private WhereParameter _AnswerID_W = null;
			private WhereParameter _QuestionID_W = null;
			private WhereParameter _AnswerText_W = null;

			public void WhereClauseReset()
			{
				_SurveyMemberAnwerID_W = null;
				_SurveyMemberID_W = null;
				_AnswerID_W = null;
				_QuestionID_W = null;
				_AnswerText_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter SurveyMemberAnwerID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.SurveyMemberAnwerID, Parameters.SurveyMemberAnwerID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter SurveyMemberID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.SurveyMemberID, Parameters.SurveyMemberID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter AnswerID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.AnswerID, Parameters.AnswerID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter QuestionID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.QuestionID, Parameters.QuestionID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter AnswerText
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.AnswerText, Parameters.AnswerText);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter SurveyMemberAnwerID
		    {
				get
		        {
					if(_SurveyMemberAnwerID_W == null)
	        	    {
						_SurveyMemberAnwerID_W = TearOff.SurveyMemberAnwerID;
					}
					return _SurveyMemberAnwerID_W;
				}
			}

			public AggregateParameter SurveyMemberID
		    {
				get
		        {
					if(_SurveyMemberID_W == null)
	        	    {
						_SurveyMemberID_W = TearOff.SurveyMemberID;
					}
					return _SurveyMemberID_W;
				}
			}

			public AggregateParameter AnswerID
		    {
				get
		        {
					if(_AnswerID_W == null)
	        	    {
						_AnswerID_W = TearOff.AnswerID;
					}
					return _AnswerID_W;
				}
			}

			public AggregateParameter QuestionID
		    {
				get
		        {
					if(_QuestionID_W == null)
	        	    {
						_QuestionID_W = TearOff.QuestionID;
					}
					return _QuestionID_W;
				}
			}

			public AggregateParameter AnswerText
		    {
				get
		        {
					if(_AnswerText_W == null)
	        	    {
						_AnswerText_W = TearOff.AnswerText;
					}
					return _AnswerText_W;
				}
			}

			private AggregateParameter _SurveyMemberAnwerID_W = null;
			private AggregateParameter _SurveyMemberID_W = null;
			private AggregateParameter _AnswerID_W = null;
			private AggregateParameter _QuestionID_W = null;
			private AggregateParameter _AnswerText_W = null;

			public void AggregateClauseReset()
			{
				_SurveyMemberAnwerID_W = null;
				_SurveyMemberID_W = null;
				_AnswerID_W = null;
				_QuestionID_W = null;
				_AnswerText_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_SurveyMemberAnswerInsert]";
	
			CreateParameters(cmd);
			
			SqlParameter p;
			p = cmd.Parameters[Parameters.SurveyMemberAnwerID.ParameterName];
			p.Direction = ParameterDirection.Output;
    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_SurveyMemberAnswerUpdate]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_SurveyMemberAnswerDelete]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.SurveyMemberAnwerID);
			p.SourceColumn = ColumnNames.SurveyMemberAnwerID;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.SurveyMemberAnwerID);
			p.SourceColumn = ColumnNames.SurveyMemberAnwerID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.SurveyMemberID);
			p.SourceColumn = ColumnNames.SurveyMemberID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.AnswerID);
			p.SourceColumn = ColumnNames.AnswerID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.QuestionID);
			p.SourceColumn = ColumnNames.QuestionID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.AnswerText);
			p.SourceColumn = ColumnNames.AnswerText;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
