
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

using MyGeneration.dOOdads;

namespace GrowSurv.DAL
{
	public abstract class _SurveyMember : SqlClientEntity
	{
		public _SurveyMember()
		{
			this.QuerySource = "SurveyMember";
			this.MappingName = "SurveyMember";

		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_SurveyMemberLoadAll]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int MemberID)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.MemberID, MemberID);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_SurveyMemberLoadByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter MemberID
			{
				get
				{
					return new SqlParameter("@MemberID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter MemberEmail
			{
				get
				{
					return new SqlParameter("@MemberEmail", SqlDbType.NVarChar, 500);
				}
			}
			
			public static SqlParameter SurveyID
			{
				get
				{
					return new SqlParameter("@SurveyID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter DivionID
			{
				get
				{
					return new SqlParameter("@DivionID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter DepartmentID
			{
				get
				{
					return new SqlParameter("@DepartmentID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter AreaID
			{
				get
				{
					return new SqlParameter("@AreaID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter BranchID
			{
				get
				{
					return new SqlParameter("@BranchID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter GradeID
			{
				get
				{
					return new SqlParameter("@GradeID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter LevelID
			{
				get
				{
					return new SqlParameter("@LevelID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter JobTitleID
			{
				get
				{
					return new SqlParameter("@JobTitleID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter GenderID
			{
				get
				{
					return new SqlParameter("@GenderID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter AgeGroupID
			{
				get
				{
					return new SqlParameter("@AgeGroupID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter Duration
			{
				get
				{
					return new SqlParameter("@Duration", SqlDbType.DateTime, 0);
				}
			}
			
			public static SqlParameter RecentPromotionDate
			{
				get
				{
					return new SqlParameter("@RecentPromotionDate", SqlDbType.DateTime, 0);
				}
			}
			
			public static SqlParameter GovernrateID
			{
				get
				{
					return new SqlParameter("@GovernrateID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter IsSurveySubmited
			{
				get
				{
					return new SqlParameter("@IsSurveySubmited", SqlDbType.Bit, 0);
				}
			}
			
			public static SqlParameter SubmitDate
			{
				get
				{
					return new SqlParameter("@SubmitDate", SqlDbType.DateTime, 0);
				}
			}
			
			public static SqlParameter CountryID
			{
				get
				{
					return new SqlParameter("@CountryID", SqlDbType.Int, 0);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string MemberID = "MemberID";
            public const string MemberEmail = "MemberEmail";
            public const string SurveyID = "SurveyID";
            public const string DivionID = "DivionID";
            public const string DepartmentID = "DepartmentID";
            public const string AreaID = "AreaID";
            public const string BranchID = "BranchID";
            public const string GradeID = "GradeID";
            public const string LevelID = "LevelID";
            public const string JobTitleID = "JobTitleID";
            public const string GenderID = "GenderID";
            public const string AgeGroupID = "AgeGroupID";
            public const string Duration = "Duration";
            public const string RecentPromotionDate = "RecentPromotionDate";
            public const string GovernrateID = "GovernrateID";
            public const string IsSurveySubmited = "IsSurveySubmited";
            public const string SubmitDate = "SubmitDate";
            public const string CountryID = "CountryID";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[MemberID] = _SurveyMember.PropertyNames.MemberID;
					ht[MemberEmail] = _SurveyMember.PropertyNames.MemberEmail;
					ht[SurveyID] = _SurveyMember.PropertyNames.SurveyID;
					ht[DivionID] = _SurveyMember.PropertyNames.DivionID;
					ht[DepartmentID] = _SurveyMember.PropertyNames.DepartmentID;
					ht[AreaID] = _SurveyMember.PropertyNames.AreaID;
					ht[BranchID] = _SurveyMember.PropertyNames.BranchID;
					ht[GradeID] = _SurveyMember.PropertyNames.GradeID;
					ht[LevelID] = _SurveyMember.PropertyNames.LevelID;
					ht[JobTitleID] = _SurveyMember.PropertyNames.JobTitleID;
					ht[GenderID] = _SurveyMember.PropertyNames.GenderID;
					ht[AgeGroupID] = _SurveyMember.PropertyNames.AgeGroupID;
					ht[Duration] = _SurveyMember.PropertyNames.Duration;
					ht[RecentPromotionDate] = _SurveyMember.PropertyNames.RecentPromotionDate;
					ht[GovernrateID] = _SurveyMember.PropertyNames.GovernrateID;
					ht[IsSurveySubmited] = _SurveyMember.PropertyNames.IsSurveySubmited;
					ht[SubmitDate] = _SurveyMember.PropertyNames.SubmitDate;
					ht[CountryID] = _SurveyMember.PropertyNames.CountryID;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string MemberID = "MemberID";
            public const string MemberEmail = "MemberEmail";
            public const string SurveyID = "SurveyID";
            public const string DivionID = "DivionID";
            public const string DepartmentID = "DepartmentID";
            public const string AreaID = "AreaID";
            public const string BranchID = "BranchID";
            public const string GradeID = "GradeID";
            public const string LevelID = "LevelID";
            public const string JobTitleID = "JobTitleID";
            public const string GenderID = "GenderID";
            public const string AgeGroupID = "AgeGroupID";
            public const string Duration = "Duration";
            public const string RecentPromotionDate = "RecentPromotionDate";
            public const string GovernrateID = "GovernrateID";
            public const string IsSurveySubmited = "IsSurveySubmited";
            public const string SubmitDate = "SubmitDate";
            public const string CountryID = "CountryID";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[MemberID] = _SurveyMember.ColumnNames.MemberID;
					ht[MemberEmail] = _SurveyMember.ColumnNames.MemberEmail;
					ht[SurveyID] = _SurveyMember.ColumnNames.SurveyID;
					ht[DivionID] = _SurveyMember.ColumnNames.DivionID;
					ht[DepartmentID] = _SurveyMember.ColumnNames.DepartmentID;
					ht[AreaID] = _SurveyMember.ColumnNames.AreaID;
					ht[BranchID] = _SurveyMember.ColumnNames.BranchID;
					ht[GradeID] = _SurveyMember.ColumnNames.GradeID;
					ht[LevelID] = _SurveyMember.ColumnNames.LevelID;
					ht[JobTitleID] = _SurveyMember.ColumnNames.JobTitleID;
					ht[GenderID] = _SurveyMember.ColumnNames.GenderID;
					ht[AgeGroupID] = _SurveyMember.ColumnNames.AgeGroupID;
					ht[Duration] = _SurveyMember.ColumnNames.Duration;
					ht[RecentPromotionDate] = _SurveyMember.ColumnNames.RecentPromotionDate;
					ht[GovernrateID] = _SurveyMember.ColumnNames.GovernrateID;
					ht[IsSurveySubmited] = _SurveyMember.ColumnNames.IsSurveySubmited;
					ht[SubmitDate] = _SurveyMember.ColumnNames.SubmitDate;
					ht[CountryID] = _SurveyMember.ColumnNames.CountryID;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string MemberID = "s_MemberID";
            public const string MemberEmail = "s_MemberEmail";
            public const string SurveyID = "s_SurveyID";
            public const string DivionID = "s_DivionID";
            public const string DepartmentID = "s_DepartmentID";
            public const string AreaID = "s_AreaID";
            public const string BranchID = "s_BranchID";
            public const string GradeID = "s_GradeID";
            public const string LevelID = "s_LevelID";
            public const string JobTitleID = "s_JobTitleID";
            public const string GenderID = "s_GenderID";
            public const string AgeGroupID = "s_AgeGroupID";
            public const string Duration = "s_Duration";
            public const string RecentPromotionDate = "s_RecentPromotionDate";
            public const string GovernrateID = "s_GovernrateID";
            public const string IsSurveySubmited = "s_IsSurveySubmited";
            public const string SubmitDate = "s_SubmitDate";
            public const string CountryID = "s_CountryID";

		}
		#endregion		
		
		#region Properties
	
		public virtual int MemberID
	    {
			get
	        {
				return base.Getint(ColumnNames.MemberID);
			}
			set
	        {
				base.Setint(ColumnNames.MemberID, value);
			}
		}

		public virtual string MemberEmail
	    {
			get
	        {
				return base.Getstring(ColumnNames.MemberEmail);
			}
			set
	        {
				base.Setstring(ColumnNames.MemberEmail, value);
			}
		}

		public virtual int SurveyID
	    {
			get
	        {
				return base.Getint(ColumnNames.SurveyID);
			}
			set
	        {
				base.Setint(ColumnNames.SurveyID, value);
			}
		}

		public virtual int DivionID
	    {
			get
	        {
				return base.Getint(ColumnNames.DivionID);
			}
			set
	        {
				base.Setint(ColumnNames.DivionID, value);
			}
		}

		public virtual int DepartmentID
	    {
			get
	        {
				return base.Getint(ColumnNames.DepartmentID);
			}
			set
	        {
				base.Setint(ColumnNames.DepartmentID, value);
			}
		}

		public virtual int AreaID
	    {
			get
	        {
				return base.Getint(ColumnNames.AreaID);
			}
			set
	        {
				base.Setint(ColumnNames.AreaID, value);
			}
		}

		public virtual int BranchID
	    {
			get
	        {
				return base.Getint(ColumnNames.BranchID);
			}
			set
	        {
				base.Setint(ColumnNames.BranchID, value);
			}
		}

		public virtual int GradeID
	    {
			get
	        {
				return base.Getint(ColumnNames.GradeID);
			}
			set
	        {
				base.Setint(ColumnNames.GradeID, value);
			}
		}

		public virtual int LevelID
	    {
			get
	        {
				return base.Getint(ColumnNames.LevelID);
			}
			set
	        {
				base.Setint(ColumnNames.LevelID, value);
			}
		}

		public virtual int JobTitleID
	    {
			get
	        {
				return base.Getint(ColumnNames.JobTitleID);
			}
			set
	        {
				base.Setint(ColumnNames.JobTitleID, value);
			}
		}

		public virtual int GenderID
	    {
			get
	        {
				return base.Getint(ColumnNames.GenderID);
			}
			set
	        {
				base.Setint(ColumnNames.GenderID, value);
			}
		}

		public virtual int AgeGroupID
	    {
			get
	        {
				return base.Getint(ColumnNames.AgeGroupID);
			}
			set
	        {
				base.Setint(ColumnNames.AgeGroupID, value);
			}
		}

		public virtual DateTime Duration
	    {
			get
	        {
				return base.GetDateTime(ColumnNames.Duration);
			}
			set
	        {
				base.SetDateTime(ColumnNames.Duration, value);
			}
		}

		public virtual DateTime RecentPromotionDate
	    {
			get
	        {
				return base.GetDateTime(ColumnNames.RecentPromotionDate);
			}
			set
	        {
				base.SetDateTime(ColumnNames.RecentPromotionDate, value);
			}
		}

		public virtual int GovernrateID
	    {
			get
	        {
				return base.Getint(ColumnNames.GovernrateID);
			}
			set
	        {
				base.Setint(ColumnNames.GovernrateID, value);
			}
		}

		public virtual bool IsSurveySubmited
	    {
			get
	        {
				return base.Getbool(ColumnNames.IsSurveySubmited);
			}
			set
	        {
				base.Setbool(ColumnNames.IsSurveySubmited, value);
			}
		}

		public virtual DateTime SubmitDate
	    {
			get
	        {
				return base.GetDateTime(ColumnNames.SubmitDate);
			}
			set
	        {
				base.SetDateTime(ColumnNames.SubmitDate, value);
			}
		}

		public virtual int CountryID
	    {
			get
	        {
				return base.Getint(ColumnNames.CountryID);
			}
			set
	        {
				base.Setint(ColumnNames.CountryID, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_MemberID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.MemberID) ? string.Empty : base.GetintAsString(ColumnNames.MemberID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.MemberID);
				else
					this.MemberID = base.SetintAsString(ColumnNames.MemberID, value);
			}
		}

		public virtual string s_MemberEmail
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.MemberEmail) ? string.Empty : base.GetstringAsString(ColumnNames.MemberEmail);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.MemberEmail);
				else
					this.MemberEmail = base.SetstringAsString(ColumnNames.MemberEmail, value);
			}
		}

		public virtual string s_SurveyID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.SurveyID) ? string.Empty : base.GetintAsString(ColumnNames.SurveyID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.SurveyID);
				else
					this.SurveyID = base.SetintAsString(ColumnNames.SurveyID, value);
			}
		}

		public virtual string s_DivionID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.DivionID) ? string.Empty : base.GetintAsString(ColumnNames.DivionID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.DivionID);
				else
					this.DivionID = base.SetintAsString(ColumnNames.DivionID, value);
			}
		}

		public virtual string s_DepartmentID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.DepartmentID) ? string.Empty : base.GetintAsString(ColumnNames.DepartmentID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.DepartmentID);
				else
					this.DepartmentID = base.SetintAsString(ColumnNames.DepartmentID, value);
			}
		}

		public virtual string s_AreaID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.AreaID) ? string.Empty : base.GetintAsString(ColumnNames.AreaID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.AreaID);
				else
					this.AreaID = base.SetintAsString(ColumnNames.AreaID, value);
			}
		}

		public virtual string s_BranchID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.BranchID) ? string.Empty : base.GetintAsString(ColumnNames.BranchID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.BranchID);
				else
					this.BranchID = base.SetintAsString(ColumnNames.BranchID, value);
			}
		}

		public virtual string s_GradeID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.GradeID) ? string.Empty : base.GetintAsString(ColumnNames.GradeID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.GradeID);
				else
					this.GradeID = base.SetintAsString(ColumnNames.GradeID, value);
			}
		}

		public virtual string s_LevelID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.LevelID) ? string.Empty : base.GetintAsString(ColumnNames.LevelID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.LevelID);
				else
					this.LevelID = base.SetintAsString(ColumnNames.LevelID, value);
			}
		}

		public virtual string s_JobTitleID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.JobTitleID) ? string.Empty : base.GetintAsString(ColumnNames.JobTitleID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.JobTitleID);
				else
					this.JobTitleID = base.SetintAsString(ColumnNames.JobTitleID, value);
			}
		}

		public virtual string s_GenderID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.GenderID) ? string.Empty : base.GetintAsString(ColumnNames.GenderID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.GenderID);
				else
					this.GenderID = base.SetintAsString(ColumnNames.GenderID, value);
			}
		}

		public virtual string s_AgeGroupID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.AgeGroupID) ? string.Empty : base.GetintAsString(ColumnNames.AgeGroupID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.AgeGroupID);
				else
					this.AgeGroupID = base.SetintAsString(ColumnNames.AgeGroupID, value);
			}
		}

		public virtual string s_Duration
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Duration) ? string.Empty : base.GetDateTimeAsString(ColumnNames.Duration);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Duration);
				else
					this.Duration = base.SetDateTimeAsString(ColumnNames.Duration, value);
			}
		}

		public virtual string s_RecentPromotionDate
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.RecentPromotionDate) ? string.Empty : base.GetDateTimeAsString(ColumnNames.RecentPromotionDate);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.RecentPromotionDate);
				else
					this.RecentPromotionDate = base.SetDateTimeAsString(ColumnNames.RecentPromotionDate, value);
			}
		}

		public virtual string s_GovernrateID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.GovernrateID) ? string.Empty : base.GetintAsString(ColumnNames.GovernrateID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.GovernrateID);
				else
					this.GovernrateID = base.SetintAsString(ColumnNames.GovernrateID, value);
			}
		}

		public virtual string s_IsSurveySubmited
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.IsSurveySubmited) ? string.Empty : base.GetboolAsString(ColumnNames.IsSurveySubmited);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.IsSurveySubmited);
				else
					this.IsSurveySubmited = base.SetboolAsString(ColumnNames.IsSurveySubmited, value);
			}
		}

		public virtual string s_SubmitDate
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.SubmitDate) ? string.Empty : base.GetDateTimeAsString(ColumnNames.SubmitDate);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.SubmitDate);
				else
					this.SubmitDate = base.SetDateTimeAsString(ColumnNames.SubmitDate, value);
			}
		}

		public virtual string s_CountryID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.CountryID) ? string.Empty : base.GetintAsString(ColumnNames.CountryID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.CountryID);
				else
					this.CountryID = base.SetintAsString(ColumnNames.CountryID, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter MemberID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.MemberID, Parameters.MemberID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter MemberEmail
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.MemberEmail, Parameters.MemberEmail);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter SurveyID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.SurveyID, Parameters.SurveyID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter DivionID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.DivionID, Parameters.DivionID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter DepartmentID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.DepartmentID, Parameters.DepartmentID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter AreaID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.AreaID, Parameters.AreaID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter BranchID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.BranchID, Parameters.BranchID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter GradeID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.GradeID, Parameters.GradeID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter LevelID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.LevelID, Parameters.LevelID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter JobTitleID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.JobTitleID, Parameters.JobTitleID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter GenderID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.GenderID, Parameters.GenderID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter AgeGroupID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.AgeGroupID, Parameters.AgeGroupID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Duration
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Duration, Parameters.Duration);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter RecentPromotionDate
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.RecentPromotionDate, Parameters.RecentPromotionDate);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter GovernrateID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.GovernrateID, Parameters.GovernrateID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter IsSurveySubmited
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.IsSurveySubmited, Parameters.IsSurveySubmited);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter SubmitDate
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.SubmitDate, Parameters.SubmitDate);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter CountryID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.CountryID, Parameters.CountryID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter MemberID
		    {
				get
		        {
					if(_MemberID_W == null)
	        	    {
						_MemberID_W = TearOff.MemberID;
					}
					return _MemberID_W;
				}
			}

			public WhereParameter MemberEmail
		    {
				get
		        {
					if(_MemberEmail_W == null)
	        	    {
						_MemberEmail_W = TearOff.MemberEmail;
					}
					return _MemberEmail_W;
				}
			}

			public WhereParameter SurveyID
		    {
				get
		        {
					if(_SurveyID_W == null)
	        	    {
						_SurveyID_W = TearOff.SurveyID;
					}
					return _SurveyID_W;
				}
			}

			public WhereParameter DivionID
		    {
				get
		        {
					if(_DivionID_W == null)
	        	    {
						_DivionID_W = TearOff.DivionID;
					}
					return _DivionID_W;
				}
			}

			public WhereParameter DepartmentID
		    {
				get
		        {
					if(_DepartmentID_W == null)
	        	    {
						_DepartmentID_W = TearOff.DepartmentID;
					}
					return _DepartmentID_W;
				}
			}

			public WhereParameter AreaID
		    {
				get
		        {
					if(_AreaID_W == null)
	        	    {
						_AreaID_W = TearOff.AreaID;
					}
					return _AreaID_W;
				}
			}

			public WhereParameter BranchID
		    {
				get
		        {
					if(_BranchID_W == null)
	        	    {
						_BranchID_W = TearOff.BranchID;
					}
					return _BranchID_W;
				}
			}

			public WhereParameter GradeID
		    {
				get
		        {
					if(_GradeID_W == null)
	        	    {
						_GradeID_W = TearOff.GradeID;
					}
					return _GradeID_W;
				}
			}

			public WhereParameter LevelID
		    {
				get
		        {
					if(_LevelID_W == null)
	        	    {
						_LevelID_W = TearOff.LevelID;
					}
					return _LevelID_W;
				}
			}

			public WhereParameter JobTitleID
		    {
				get
		        {
					if(_JobTitleID_W == null)
	        	    {
						_JobTitleID_W = TearOff.JobTitleID;
					}
					return _JobTitleID_W;
				}
			}

			public WhereParameter GenderID
		    {
				get
		        {
					if(_GenderID_W == null)
	        	    {
						_GenderID_W = TearOff.GenderID;
					}
					return _GenderID_W;
				}
			}

			public WhereParameter AgeGroupID
		    {
				get
		        {
					if(_AgeGroupID_W == null)
	        	    {
						_AgeGroupID_W = TearOff.AgeGroupID;
					}
					return _AgeGroupID_W;
				}
			}

			public WhereParameter Duration
		    {
				get
		        {
					if(_Duration_W == null)
	        	    {
						_Duration_W = TearOff.Duration;
					}
					return _Duration_W;
				}
			}

			public WhereParameter RecentPromotionDate
		    {
				get
		        {
					if(_RecentPromotionDate_W == null)
	        	    {
						_RecentPromotionDate_W = TearOff.RecentPromotionDate;
					}
					return _RecentPromotionDate_W;
				}
			}

			public WhereParameter GovernrateID
		    {
				get
		        {
					if(_GovernrateID_W == null)
	        	    {
						_GovernrateID_W = TearOff.GovernrateID;
					}
					return _GovernrateID_W;
				}
			}

			public WhereParameter IsSurveySubmited
		    {
				get
		        {
					if(_IsSurveySubmited_W == null)
	        	    {
						_IsSurveySubmited_W = TearOff.IsSurveySubmited;
					}
					return _IsSurveySubmited_W;
				}
			}

			public WhereParameter SubmitDate
		    {
				get
		        {
					if(_SubmitDate_W == null)
	        	    {
						_SubmitDate_W = TearOff.SubmitDate;
					}
					return _SubmitDate_W;
				}
			}

			public WhereParameter CountryID
		    {
				get
		        {
					if(_CountryID_W == null)
	        	    {
						_CountryID_W = TearOff.CountryID;
					}
					return _CountryID_W;
				}
			}

			private WhereParameter _MemberID_W = null;
			private WhereParameter _MemberEmail_W = null;
			private WhereParameter _SurveyID_W = null;
			private WhereParameter _DivionID_W = null;
			private WhereParameter _DepartmentID_W = null;
			private WhereParameter _AreaID_W = null;
			private WhereParameter _BranchID_W = null;
			private WhereParameter _GradeID_W = null;
			private WhereParameter _LevelID_W = null;
			private WhereParameter _JobTitleID_W = null;
			private WhereParameter _GenderID_W = null;
			private WhereParameter _AgeGroupID_W = null;
			private WhereParameter _Duration_W = null;
			private WhereParameter _RecentPromotionDate_W = null;
			private WhereParameter _GovernrateID_W = null;
			private WhereParameter _IsSurveySubmited_W = null;
			private WhereParameter _SubmitDate_W = null;
			private WhereParameter _CountryID_W = null;

			public void WhereClauseReset()
			{
				_MemberID_W = null;
				_MemberEmail_W = null;
				_SurveyID_W = null;
				_DivionID_W = null;
				_DepartmentID_W = null;
				_AreaID_W = null;
				_BranchID_W = null;
				_GradeID_W = null;
				_LevelID_W = null;
				_JobTitleID_W = null;
				_GenderID_W = null;
				_AgeGroupID_W = null;
				_Duration_W = null;
				_RecentPromotionDate_W = null;
				_GovernrateID_W = null;
				_IsSurveySubmited_W = null;
				_SubmitDate_W = null;
				_CountryID_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter MemberID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.MemberID, Parameters.MemberID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter MemberEmail
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.MemberEmail, Parameters.MemberEmail);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter SurveyID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.SurveyID, Parameters.SurveyID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter DivionID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.DivionID, Parameters.DivionID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter DepartmentID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.DepartmentID, Parameters.DepartmentID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter AreaID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.AreaID, Parameters.AreaID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter BranchID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.BranchID, Parameters.BranchID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter GradeID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.GradeID, Parameters.GradeID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter LevelID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.LevelID, Parameters.LevelID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter JobTitleID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.JobTitleID, Parameters.JobTitleID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter GenderID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.GenderID, Parameters.GenderID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter AgeGroupID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.AgeGroupID, Parameters.AgeGroupID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Duration
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Duration, Parameters.Duration);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter RecentPromotionDate
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.RecentPromotionDate, Parameters.RecentPromotionDate);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter GovernrateID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.GovernrateID, Parameters.GovernrateID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter IsSurveySubmited
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.IsSurveySubmited, Parameters.IsSurveySubmited);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter SubmitDate
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.SubmitDate, Parameters.SubmitDate);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter CountryID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.CountryID, Parameters.CountryID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter MemberID
		    {
				get
		        {
					if(_MemberID_W == null)
	        	    {
						_MemberID_W = TearOff.MemberID;
					}
					return _MemberID_W;
				}
			}

			public AggregateParameter MemberEmail
		    {
				get
		        {
					if(_MemberEmail_W == null)
	        	    {
						_MemberEmail_W = TearOff.MemberEmail;
					}
					return _MemberEmail_W;
				}
			}

			public AggregateParameter SurveyID
		    {
				get
		        {
					if(_SurveyID_W == null)
	        	    {
						_SurveyID_W = TearOff.SurveyID;
					}
					return _SurveyID_W;
				}
			}

			public AggregateParameter DivionID
		    {
				get
		        {
					if(_DivionID_W == null)
	        	    {
						_DivionID_W = TearOff.DivionID;
					}
					return _DivionID_W;
				}
			}

			public AggregateParameter DepartmentID
		    {
				get
		        {
					if(_DepartmentID_W == null)
	        	    {
						_DepartmentID_W = TearOff.DepartmentID;
					}
					return _DepartmentID_W;
				}
			}

			public AggregateParameter AreaID
		    {
				get
		        {
					if(_AreaID_W == null)
	        	    {
						_AreaID_W = TearOff.AreaID;
					}
					return _AreaID_W;
				}
			}

			public AggregateParameter BranchID
		    {
				get
		        {
					if(_BranchID_W == null)
	        	    {
						_BranchID_W = TearOff.BranchID;
					}
					return _BranchID_W;
				}
			}

			public AggregateParameter GradeID
		    {
				get
		        {
					if(_GradeID_W == null)
	        	    {
						_GradeID_W = TearOff.GradeID;
					}
					return _GradeID_W;
				}
			}

			public AggregateParameter LevelID
		    {
				get
		        {
					if(_LevelID_W == null)
	        	    {
						_LevelID_W = TearOff.LevelID;
					}
					return _LevelID_W;
				}
			}

			public AggregateParameter JobTitleID
		    {
				get
		        {
					if(_JobTitleID_W == null)
	        	    {
						_JobTitleID_W = TearOff.JobTitleID;
					}
					return _JobTitleID_W;
				}
			}

			public AggregateParameter GenderID
		    {
				get
		        {
					if(_GenderID_W == null)
	        	    {
						_GenderID_W = TearOff.GenderID;
					}
					return _GenderID_W;
				}
			}

			public AggregateParameter AgeGroupID
		    {
				get
		        {
					if(_AgeGroupID_W == null)
	        	    {
						_AgeGroupID_W = TearOff.AgeGroupID;
					}
					return _AgeGroupID_W;
				}
			}

			public AggregateParameter Duration
		    {
				get
		        {
					if(_Duration_W == null)
	        	    {
						_Duration_W = TearOff.Duration;
					}
					return _Duration_W;
				}
			}

			public AggregateParameter RecentPromotionDate
		    {
				get
		        {
					if(_RecentPromotionDate_W == null)
	        	    {
						_RecentPromotionDate_W = TearOff.RecentPromotionDate;
					}
					return _RecentPromotionDate_W;
				}
			}

			public AggregateParameter GovernrateID
		    {
				get
		        {
					if(_GovernrateID_W == null)
	        	    {
						_GovernrateID_W = TearOff.GovernrateID;
					}
					return _GovernrateID_W;
				}
			}

			public AggregateParameter IsSurveySubmited
		    {
				get
		        {
					if(_IsSurveySubmited_W == null)
	        	    {
						_IsSurveySubmited_W = TearOff.IsSurveySubmited;
					}
					return _IsSurveySubmited_W;
				}
			}

			public AggregateParameter SubmitDate
		    {
				get
		        {
					if(_SubmitDate_W == null)
	        	    {
						_SubmitDate_W = TearOff.SubmitDate;
					}
					return _SubmitDate_W;
				}
			}

			public AggregateParameter CountryID
		    {
				get
		        {
					if(_CountryID_W == null)
	        	    {
						_CountryID_W = TearOff.CountryID;
					}
					return _CountryID_W;
				}
			}

			private AggregateParameter _MemberID_W = null;
			private AggregateParameter _MemberEmail_W = null;
			private AggregateParameter _SurveyID_W = null;
			private AggregateParameter _DivionID_W = null;
			private AggregateParameter _DepartmentID_W = null;
			private AggregateParameter _AreaID_W = null;
			private AggregateParameter _BranchID_W = null;
			private AggregateParameter _GradeID_W = null;
			private AggregateParameter _LevelID_W = null;
			private AggregateParameter _JobTitleID_W = null;
			private AggregateParameter _GenderID_W = null;
			private AggregateParameter _AgeGroupID_W = null;
			private AggregateParameter _Duration_W = null;
			private AggregateParameter _RecentPromotionDate_W = null;
			private AggregateParameter _GovernrateID_W = null;
			private AggregateParameter _IsSurveySubmited_W = null;
			private AggregateParameter _SubmitDate_W = null;
			private AggregateParameter _CountryID_W = null;

			public void AggregateClauseReset()
			{
				_MemberID_W = null;
				_MemberEmail_W = null;
				_SurveyID_W = null;
				_DivionID_W = null;
				_DepartmentID_W = null;
				_AreaID_W = null;
				_BranchID_W = null;
				_GradeID_W = null;
				_LevelID_W = null;
				_JobTitleID_W = null;
				_GenderID_W = null;
				_AgeGroupID_W = null;
				_Duration_W = null;
				_RecentPromotionDate_W = null;
				_GovernrateID_W = null;
				_IsSurveySubmited_W = null;
				_SubmitDate_W = null;
				_CountryID_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_SurveyMemberInsert]";
	
			CreateParameters(cmd);
			
			SqlParameter p;
			p = cmd.Parameters[Parameters.MemberID.ParameterName];
			p.Direction = ParameterDirection.Output;
    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_SurveyMemberUpdate]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_SurveyMemberDelete]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.MemberID);
			p.SourceColumn = ColumnNames.MemberID;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.MemberID);
			p.SourceColumn = ColumnNames.MemberID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.MemberEmail);
			p.SourceColumn = ColumnNames.MemberEmail;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.SurveyID);
			p.SourceColumn = ColumnNames.SurveyID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.DivionID);
			p.SourceColumn = ColumnNames.DivionID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.DepartmentID);
			p.SourceColumn = ColumnNames.DepartmentID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.AreaID);
			p.SourceColumn = ColumnNames.AreaID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.BranchID);
			p.SourceColumn = ColumnNames.BranchID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.GradeID);
			p.SourceColumn = ColumnNames.GradeID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.LevelID);
			p.SourceColumn = ColumnNames.LevelID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.JobTitleID);
			p.SourceColumn = ColumnNames.JobTitleID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.GenderID);
			p.SourceColumn = ColumnNames.GenderID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.AgeGroupID);
			p.SourceColumn = ColumnNames.AgeGroupID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Duration);
			p.SourceColumn = ColumnNames.Duration;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.RecentPromotionDate);
			p.SourceColumn = ColumnNames.RecentPromotionDate;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.GovernrateID);
			p.SourceColumn = ColumnNames.GovernrateID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.IsSurveySubmited);
			p.SourceColumn = ColumnNames.IsSurveySubmited;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.SubmitDate);
			p.SourceColumn = ColumnNames.SubmitDate;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.CountryID);
			p.SourceColumn = ColumnNames.CountryID;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
