
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

using MyGeneration.dOOdads;

namespace GrowSurv.DAL
{
	public abstract class _Survey : SqlClientEntity
	{
		public _Survey()
		{
			this.QuerySource = "Survey";
			this.MappingName = "Survey";

		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_SurveyLoadAll]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int SurveyID)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.SurveyID, SurveyID);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_SurveyLoadByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter SurveyID
			{
				get
				{
					return new SqlParameter("@SurveyID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter ArName
			{
				get
				{
					return new SqlParameter("@ArName", SqlDbType.NVarChar, 200);
				}
			}
			
			public static SqlParameter EnName
			{
				get
				{
					return new SqlParameter("@EnName", SqlDbType.NVarChar, 200);
				}
			}
			
			public static SqlParameter ArDesc
			{
				get
				{
					return new SqlParameter("@ArDesc", SqlDbType.NVarChar, 2000);
				}
			}
			
			public static SqlParameter EnDesc
			{
				get
				{
					return new SqlParameter("@EnDesc", SqlDbType.NVarChar, 2000);
				}
			}
			
			public static SqlParameter CompanyID
			{
				get
				{
					return new SqlParameter("@CompanyID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter ExpiryDate
			{
				get
				{
					return new SqlParameter("@ExpiryDate", SqlDbType.DateTime, 0);
				}
			}
			
			public static SqlParameter IsDivisionMandatory
			{
				get
				{
					return new SqlParameter("@IsDivisionMandatory", SqlDbType.Bit, 0);
				}
			}
			
			public static SqlParameter IsDepartmentMandatory
			{
				get
				{
					return new SqlParameter("@IsDepartmentMandatory", SqlDbType.Bit, 0);
				}
			}
			
			public static SqlParameter IsAreaMandatory
			{
				get
				{
					return new SqlParameter("@IsAreaMandatory", SqlDbType.Bit, 0);
				}
			}
			
			public static SqlParameter IsBranchMandatory
			{
				get
				{
					return new SqlParameter("@IsBranchMandatory", SqlDbType.Bit, 0);
				}
			}
			
			public static SqlParameter IsGradeMandatory
			{
				get
				{
					return new SqlParameter("@IsGradeMandatory", SqlDbType.Bit, 0);
				}
			}
			
			public static SqlParameter IsLevelMandatory
			{
				get
				{
					return new SqlParameter("@IsLevelMandatory", SqlDbType.Bit, 0);
				}
			}
			
			public static SqlParameter IsJobTitleMandatory
			{
				get
				{
					return new SqlParameter("@IsJobTitleMandatory", SqlDbType.Bit, 0);
				}
			}
			
			public static SqlParameter IsGenderMandatory
			{
				get
				{
					return new SqlParameter("@IsGenderMandatory", SqlDbType.Bit, 0);
				}
			}
			
			public static SqlParameter IsAgeMandatory
			{
				get
				{
					return new SqlParameter("@IsAgeMandatory", SqlDbType.Bit, 0);
				}
			}
			
			public static SqlParameter IsDurationMandatory
			{
				get
				{
					return new SqlParameter("@IsDurationMandatory", SqlDbType.Bit, 0);
				}
			}
			
			public static SqlParameter IsRecentPromotionDateMandatory
			{
				get
				{
					return new SqlParameter("@IsRecentPromotionDateMandatory", SqlDbType.Bit, 0);
				}
			}
			
			public static SqlParameter SurveyTypeID
			{
				get
				{
					return new SqlParameter("@SurveyTypeID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter Duration
			{
				get
				{
					return new SqlParameter("@Duration", SqlDbType.DateTime, 0);
				}
			}
			
			public static SqlParameter IsGovernrateMandatory
			{
				get
				{
					return new SqlParameter("@IsGovernrateMandatory", SqlDbType.Bit, 0);
				}
			}
			
			public static SqlParameter ArHeader
			{
				get
				{
					return new SqlParameter("@ArHeader", SqlDbType.NVarChar, 2000);
				}
			}
			
			public static SqlParameter EnHeader
			{
				get
				{
					return new SqlParameter("@EnHeader", SqlDbType.NVarChar, 2000);
				}
			}
			
			public static SqlParameter ArFooter
			{
				get
				{
					return new SqlParameter("@ArFooter", SqlDbType.NVarChar, 2000);
				}
			}
			
			public static SqlParameter EnFooter
			{
				get
				{
					return new SqlParameter("@EnFooter", SqlDbType.NVarChar, 2000);
				}
			}
			
			public static SqlParameter EmailSubject
			{
				get
				{
					return new SqlParameter("@EmailSubject", SqlDbType.NVarChar, 1000);
				}
			}
			
			public static SqlParameter EmailBody
			{
				get
				{
					return new SqlParameter("@EmailBody", SqlDbType.NVarChar, 1073741823);
				}
			}
			
			public static SqlParameter SkipDemographicPage
			{
				get
				{
					return new SqlParameter("@SkipDemographicPage", SqlDbType.Bit, 0);
				}
			}
			
			public static SqlParameter ArEmailBody
			{
				get
				{
					return new SqlParameter("@ArEmailBody", SqlDbType.NVarChar, 1073741823);
				}
			}
			
			public static SqlParameter IsPublic
			{
				get
				{
					return new SqlParameter("@IsPublic", SqlDbType.Bit, 0);
				}
			}
			
			public static SqlParameter IsCountryMandatory
			{
				get
				{
					return new SqlParameter("@IsCountryMandatory", SqlDbType.Bit, 0);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string SurveyID = "SurveyID";
            public const string ArName = "ArName";
            public const string EnName = "EnName";
            public const string ArDesc = "ArDesc";
            public const string EnDesc = "EnDesc";
            public const string CompanyID = "CompanyID";
            public const string ExpiryDate = "ExpiryDate";
            public const string IsDivisionMandatory = "IsDivisionMandatory";
            public const string IsDepartmentMandatory = "IsDepartmentMandatory";
            public const string IsAreaMandatory = "IsAreaMandatory";
            public const string IsBranchMandatory = "IsBranchMandatory";
            public const string IsGradeMandatory = "IsGradeMandatory";
            public const string IsLevelMandatory = "IsLevelMandatory";
            public const string IsJobTitleMandatory = "IsJobTitleMandatory";
            public const string IsGenderMandatory = "IsGenderMandatory";
            public const string IsAgeMandatory = "IsAgeMandatory";
            public const string IsDurationMandatory = "IsDurationMandatory";
            public const string IsRecentPromotionDateMandatory = "IsRecentPromotionDateMandatory";
            public const string SurveyTypeID = "SurveyTypeID";
            public const string Duration = "Duration";
            public const string IsGovernrateMandatory = "IsGovernrateMandatory";
            public const string ArHeader = "ArHeader";
            public const string EnHeader = "EnHeader";
            public const string ArFooter = "ArFooter";
            public const string EnFooter = "EnFooter";
            public const string EmailSubject = "EmailSubject";
            public const string EmailBody = "EmailBody";
            public const string SkipDemographicPage = "SkipDemographicPage";
            public const string ArEmailBody = "ArEmailBody";
            public const string IsPublic = "IsPublic";
            public const string IsCountryMandatory = "IsCountryMandatory";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[SurveyID] = _Survey.PropertyNames.SurveyID;
					ht[ArName] = _Survey.PropertyNames.ArName;
					ht[EnName] = _Survey.PropertyNames.EnName;
					ht[ArDesc] = _Survey.PropertyNames.ArDesc;
					ht[EnDesc] = _Survey.PropertyNames.EnDesc;
					ht[CompanyID] = _Survey.PropertyNames.CompanyID;
					ht[ExpiryDate] = _Survey.PropertyNames.ExpiryDate;
					ht[IsDivisionMandatory] = _Survey.PropertyNames.IsDivisionMandatory;
					ht[IsDepartmentMandatory] = _Survey.PropertyNames.IsDepartmentMandatory;
					ht[IsAreaMandatory] = _Survey.PropertyNames.IsAreaMandatory;
					ht[IsBranchMandatory] = _Survey.PropertyNames.IsBranchMandatory;
					ht[IsGradeMandatory] = _Survey.PropertyNames.IsGradeMandatory;
					ht[IsLevelMandatory] = _Survey.PropertyNames.IsLevelMandatory;
					ht[IsJobTitleMandatory] = _Survey.PropertyNames.IsJobTitleMandatory;
					ht[IsGenderMandatory] = _Survey.PropertyNames.IsGenderMandatory;
					ht[IsAgeMandatory] = _Survey.PropertyNames.IsAgeMandatory;
					ht[IsDurationMandatory] = _Survey.PropertyNames.IsDurationMandatory;
					ht[IsRecentPromotionDateMandatory] = _Survey.PropertyNames.IsRecentPromotionDateMandatory;
					ht[SurveyTypeID] = _Survey.PropertyNames.SurveyTypeID;
					ht[Duration] = _Survey.PropertyNames.Duration;
					ht[IsGovernrateMandatory] = _Survey.PropertyNames.IsGovernrateMandatory;
					ht[ArHeader] = _Survey.PropertyNames.ArHeader;
					ht[EnHeader] = _Survey.PropertyNames.EnHeader;
					ht[ArFooter] = _Survey.PropertyNames.ArFooter;
					ht[EnFooter] = _Survey.PropertyNames.EnFooter;
					ht[EmailSubject] = _Survey.PropertyNames.EmailSubject;
					ht[EmailBody] = _Survey.PropertyNames.EmailBody;
					ht[SkipDemographicPage] = _Survey.PropertyNames.SkipDemographicPage;
					ht[ArEmailBody] = _Survey.PropertyNames.ArEmailBody;
					ht[IsPublic] = _Survey.PropertyNames.IsPublic;
					ht[IsCountryMandatory] = _Survey.PropertyNames.IsCountryMandatory;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string SurveyID = "SurveyID";
            public const string ArName = "ArName";
            public const string EnName = "EnName";
            public const string ArDesc = "ArDesc";
            public const string EnDesc = "EnDesc";
            public const string CompanyID = "CompanyID";
            public const string ExpiryDate = "ExpiryDate";
            public const string IsDivisionMandatory = "IsDivisionMandatory";
            public const string IsDepartmentMandatory = "IsDepartmentMandatory";
            public const string IsAreaMandatory = "IsAreaMandatory";
            public const string IsBranchMandatory = "IsBranchMandatory";
            public const string IsGradeMandatory = "IsGradeMandatory";
            public const string IsLevelMandatory = "IsLevelMandatory";
            public const string IsJobTitleMandatory = "IsJobTitleMandatory";
            public const string IsGenderMandatory = "IsGenderMandatory";
            public const string IsAgeMandatory = "IsAgeMandatory";
            public const string IsDurationMandatory = "IsDurationMandatory";
            public const string IsRecentPromotionDateMandatory = "IsRecentPromotionDateMandatory";
            public const string SurveyTypeID = "SurveyTypeID";
            public const string Duration = "Duration";
            public const string IsGovernrateMandatory = "IsGovernrateMandatory";
            public const string ArHeader = "ArHeader";
            public const string EnHeader = "EnHeader";
            public const string ArFooter = "ArFooter";
            public const string EnFooter = "EnFooter";
            public const string EmailSubject = "EmailSubject";
            public const string EmailBody = "EmailBody";
            public const string SkipDemographicPage = "SkipDemographicPage";
            public const string ArEmailBody = "ArEmailBody";
            public const string IsPublic = "IsPublic";
            public const string IsCountryMandatory = "IsCountryMandatory";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[SurveyID] = _Survey.ColumnNames.SurveyID;
					ht[ArName] = _Survey.ColumnNames.ArName;
					ht[EnName] = _Survey.ColumnNames.EnName;
					ht[ArDesc] = _Survey.ColumnNames.ArDesc;
					ht[EnDesc] = _Survey.ColumnNames.EnDesc;
					ht[CompanyID] = _Survey.ColumnNames.CompanyID;
					ht[ExpiryDate] = _Survey.ColumnNames.ExpiryDate;
					ht[IsDivisionMandatory] = _Survey.ColumnNames.IsDivisionMandatory;
					ht[IsDepartmentMandatory] = _Survey.ColumnNames.IsDepartmentMandatory;
					ht[IsAreaMandatory] = _Survey.ColumnNames.IsAreaMandatory;
					ht[IsBranchMandatory] = _Survey.ColumnNames.IsBranchMandatory;
					ht[IsGradeMandatory] = _Survey.ColumnNames.IsGradeMandatory;
					ht[IsLevelMandatory] = _Survey.ColumnNames.IsLevelMandatory;
					ht[IsJobTitleMandatory] = _Survey.ColumnNames.IsJobTitleMandatory;
					ht[IsGenderMandatory] = _Survey.ColumnNames.IsGenderMandatory;
					ht[IsAgeMandatory] = _Survey.ColumnNames.IsAgeMandatory;
					ht[IsDurationMandatory] = _Survey.ColumnNames.IsDurationMandatory;
					ht[IsRecentPromotionDateMandatory] = _Survey.ColumnNames.IsRecentPromotionDateMandatory;
					ht[SurveyTypeID] = _Survey.ColumnNames.SurveyTypeID;
					ht[Duration] = _Survey.ColumnNames.Duration;
					ht[IsGovernrateMandatory] = _Survey.ColumnNames.IsGovernrateMandatory;
					ht[ArHeader] = _Survey.ColumnNames.ArHeader;
					ht[EnHeader] = _Survey.ColumnNames.EnHeader;
					ht[ArFooter] = _Survey.ColumnNames.ArFooter;
					ht[EnFooter] = _Survey.ColumnNames.EnFooter;
					ht[EmailSubject] = _Survey.ColumnNames.EmailSubject;
					ht[EmailBody] = _Survey.ColumnNames.EmailBody;
					ht[SkipDemographicPage] = _Survey.ColumnNames.SkipDemographicPage;
					ht[ArEmailBody] = _Survey.ColumnNames.ArEmailBody;
					ht[IsPublic] = _Survey.ColumnNames.IsPublic;
					ht[IsCountryMandatory] = _Survey.ColumnNames.IsCountryMandatory;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string SurveyID = "s_SurveyID";
            public const string ArName = "s_ArName";
            public const string EnName = "s_EnName";
            public const string ArDesc = "s_ArDesc";
            public const string EnDesc = "s_EnDesc";
            public const string CompanyID = "s_CompanyID";
            public const string ExpiryDate = "s_ExpiryDate";
            public const string IsDivisionMandatory = "s_IsDivisionMandatory";
            public const string IsDepartmentMandatory = "s_IsDepartmentMandatory";
            public const string IsAreaMandatory = "s_IsAreaMandatory";
            public const string IsBranchMandatory = "s_IsBranchMandatory";
            public const string IsGradeMandatory = "s_IsGradeMandatory";
            public const string IsLevelMandatory = "s_IsLevelMandatory";
            public const string IsJobTitleMandatory = "s_IsJobTitleMandatory";
            public const string IsGenderMandatory = "s_IsGenderMandatory";
            public const string IsAgeMandatory = "s_IsAgeMandatory";
            public const string IsDurationMandatory = "s_IsDurationMandatory";
            public const string IsRecentPromotionDateMandatory = "s_IsRecentPromotionDateMandatory";
            public const string SurveyTypeID = "s_SurveyTypeID";
            public const string Duration = "s_Duration";
            public const string IsGovernrateMandatory = "s_IsGovernrateMandatory";
            public const string ArHeader = "s_ArHeader";
            public const string EnHeader = "s_EnHeader";
            public const string ArFooter = "s_ArFooter";
            public const string EnFooter = "s_EnFooter";
            public const string EmailSubject = "s_EmailSubject";
            public const string EmailBody = "s_EmailBody";
            public const string SkipDemographicPage = "s_SkipDemographicPage";
            public const string ArEmailBody = "s_ArEmailBody";
            public const string IsPublic = "s_IsPublic";
            public const string IsCountryMandatory = "s_IsCountryMandatory";

		}
		#endregion		
		
		#region Properties
	
		public virtual int SurveyID
	    {
			get
	        {
				return base.Getint(ColumnNames.SurveyID);
			}
			set
	        {
				base.Setint(ColumnNames.SurveyID, value);
			}
		}

		public virtual string ArName
	    {
			get
	        {
				return base.Getstring(ColumnNames.ArName);
			}
			set
	        {
				base.Setstring(ColumnNames.ArName, value);
			}
		}

		public virtual string EnName
	    {
			get
	        {
				return base.Getstring(ColumnNames.EnName);
			}
			set
	        {
				base.Setstring(ColumnNames.EnName, value);
			}
		}

		public virtual string ArDesc
	    {
			get
	        {
				return base.Getstring(ColumnNames.ArDesc);
			}
			set
	        {
				base.Setstring(ColumnNames.ArDesc, value);
			}
		}

		public virtual string EnDesc
	    {
			get
	        {
				return base.Getstring(ColumnNames.EnDesc);
			}
			set
	        {
				base.Setstring(ColumnNames.EnDesc, value);
			}
		}

		public virtual int CompanyID
	    {
			get
	        {
				return base.Getint(ColumnNames.CompanyID);
			}
			set
	        {
				base.Setint(ColumnNames.CompanyID, value);
			}
		}

		public virtual DateTime ExpiryDate
	    {
			get
	        {
				return base.GetDateTime(ColumnNames.ExpiryDate);
			}
			set
	        {
				base.SetDateTime(ColumnNames.ExpiryDate, value);
			}
		}

		public virtual bool IsDivisionMandatory
	    {
			get
	        {
				return base.Getbool(ColumnNames.IsDivisionMandatory);
			}
			set
	        {
				base.Setbool(ColumnNames.IsDivisionMandatory, value);
			}
		}

		public virtual bool IsDepartmentMandatory
	    {
			get
	        {
				return base.Getbool(ColumnNames.IsDepartmentMandatory);
			}
			set
	        {
				base.Setbool(ColumnNames.IsDepartmentMandatory, value);
			}
		}

		public virtual bool IsAreaMandatory
	    {
			get
	        {
				return base.Getbool(ColumnNames.IsAreaMandatory);
			}
			set
	        {
				base.Setbool(ColumnNames.IsAreaMandatory, value);
			}
		}

		public virtual bool IsBranchMandatory
	    {
			get
	        {
				return base.Getbool(ColumnNames.IsBranchMandatory);
			}
			set
	        {
				base.Setbool(ColumnNames.IsBranchMandatory, value);
			}
		}

		public virtual bool IsGradeMandatory
	    {
			get
	        {
				return base.Getbool(ColumnNames.IsGradeMandatory);
			}
			set
	        {
				base.Setbool(ColumnNames.IsGradeMandatory, value);
			}
		}

		public virtual bool IsLevelMandatory
	    {
			get
	        {
				return base.Getbool(ColumnNames.IsLevelMandatory);
			}
			set
	        {
				base.Setbool(ColumnNames.IsLevelMandatory, value);
			}
		}

		public virtual bool IsJobTitleMandatory
	    {
			get
	        {
				return base.Getbool(ColumnNames.IsJobTitleMandatory);
			}
			set
	        {
				base.Setbool(ColumnNames.IsJobTitleMandatory, value);
			}
		}

		public virtual bool IsGenderMandatory
	    {
			get
	        {
				return base.Getbool(ColumnNames.IsGenderMandatory);
			}
			set
	        {
				base.Setbool(ColumnNames.IsGenderMandatory, value);
			}
		}

		public virtual bool IsAgeMandatory
	    {
			get
	        {
				return base.Getbool(ColumnNames.IsAgeMandatory);
			}
			set
	        {
				base.Setbool(ColumnNames.IsAgeMandatory, value);
			}
		}

		public virtual bool IsDurationMandatory
	    {
			get
	        {
				return base.Getbool(ColumnNames.IsDurationMandatory);
			}
			set
	        {
				base.Setbool(ColumnNames.IsDurationMandatory, value);
			}
		}

		public virtual bool IsRecentPromotionDateMandatory
	    {
			get
	        {
				return base.Getbool(ColumnNames.IsRecentPromotionDateMandatory);
			}
			set
	        {
				base.Setbool(ColumnNames.IsRecentPromotionDateMandatory, value);
			}
		}

		public virtual int SurveyTypeID
	    {
			get
	        {
				return base.Getint(ColumnNames.SurveyTypeID);
			}
			set
	        {
				base.Setint(ColumnNames.SurveyTypeID, value);
			}
		}

		public virtual DateTime Duration
	    {
			get
	        {
				return base.GetDateTime(ColumnNames.Duration);
			}
			set
	        {
				base.SetDateTime(ColumnNames.Duration, value);
			}
		}

		public virtual bool IsGovernrateMandatory
	    {
			get
	        {
				return base.Getbool(ColumnNames.IsGovernrateMandatory);
			}
			set
	        {
				base.Setbool(ColumnNames.IsGovernrateMandatory, value);
			}
		}

		public virtual string ArHeader
	    {
			get
	        {
				return base.Getstring(ColumnNames.ArHeader);
			}
			set
	        {
				base.Setstring(ColumnNames.ArHeader, value);
			}
		}

		public virtual string EnHeader
	    {
			get
	        {
				return base.Getstring(ColumnNames.EnHeader);
			}
			set
	        {
				base.Setstring(ColumnNames.EnHeader, value);
			}
		}

		public virtual string ArFooter
	    {
			get
	        {
				return base.Getstring(ColumnNames.ArFooter);
			}
			set
	        {
				base.Setstring(ColumnNames.ArFooter, value);
			}
		}

		public virtual string EnFooter
	    {
			get
	        {
				return base.Getstring(ColumnNames.EnFooter);
			}
			set
	        {
				base.Setstring(ColumnNames.EnFooter, value);
			}
		}

		public virtual string EmailSubject
	    {
			get
	        {
				return base.Getstring(ColumnNames.EmailSubject);
			}
			set
	        {
				base.Setstring(ColumnNames.EmailSubject, value);
			}
		}

		public virtual string EmailBody
	    {
			get
	        {
				return base.Getstring(ColumnNames.EmailBody);
			}
			set
	        {
				base.Setstring(ColumnNames.EmailBody, value);
			}
		}

		public virtual bool SkipDemographicPage
	    {
			get
	        {
				return base.Getbool(ColumnNames.SkipDemographicPage);
			}
			set
	        {
				base.Setbool(ColumnNames.SkipDemographicPage, value);
			}
		}

		public virtual string ArEmailBody
	    {
			get
	        {
				return base.Getstring(ColumnNames.ArEmailBody);
			}
			set
	        {
				base.Setstring(ColumnNames.ArEmailBody, value);
			}
		}

		public virtual bool IsPublic
	    {
			get
	        {
				return base.Getbool(ColumnNames.IsPublic);
			}
			set
	        {
				base.Setbool(ColumnNames.IsPublic, value);
			}
		}

		public virtual bool IsCountryMandatory
	    {
			get
	        {
				return base.Getbool(ColumnNames.IsCountryMandatory);
			}
			set
	        {
				base.Setbool(ColumnNames.IsCountryMandatory, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_SurveyID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.SurveyID) ? string.Empty : base.GetintAsString(ColumnNames.SurveyID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.SurveyID);
				else
					this.SurveyID = base.SetintAsString(ColumnNames.SurveyID, value);
			}
		}

		public virtual string s_ArName
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.ArName) ? string.Empty : base.GetstringAsString(ColumnNames.ArName);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.ArName);
				else
					this.ArName = base.SetstringAsString(ColumnNames.ArName, value);
			}
		}

		public virtual string s_EnName
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.EnName) ? string.Empty : base.GetstringAsString(ColumnNames.EnName);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.EnName);
				else
					this.EnName = base.SetstringAsString(ColumnNames.EnName, value);
			}
		}

		public virtual string s_ArDesc
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.ArDesc) ? string.Empty : base.GetstringAsString(ColumnNames.ArDesc);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.ArDesc);
				else
					this.ArDesc = base.SetstringAsString(ColumnNames.ArDesc, value);
			}
		}

		public virtual string s_EnDesc
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.EnDesc) ? string.Empty : base.GetstringAsString(ColumnNames.EnDesc);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.EnDesc);
				else
					this.EnDesc = base.SetstringAsString(ColumnNames.EnDesc, value);
			}
		}

		public virtual string s_CompanyID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.CompanyID) ? string.Empty : base.GetintAsString(ColumnNames.CompanyID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.CompanyID);
				else
					this.CompanyID = base.SetintAsString(ColumnNames.CompanyID, value);
			}
		}

		public virtual string s_ExpiryDate
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.ExpiryDate) ? string.Empty : base.GetDateTimeAsString(ColumnNames.ExpiryDate);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.ExpiryDate);
				else
					this.ExpiryDate = base.SetDateTimeAsString(ColumnNames.ExpiryDate, value);
			}
		}

		public virtual string s_IsDivisionMandatory
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.IsDivisionMandatory) ? string.Empty : base.GetboolAsString(ColumnNames.IsDivisionMandatory);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.IsDivisionMandatory);
				else
					this.IsDivisionMandatory = base.SetboolAsString(ColumnNames.IsDivisionMandatory, value);
			}
		}

		public virtual string s_IsDepartmentMandatory
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.IsDepartmentMandatory) ? string.Empty : base.GetboolAsString(ColumnNames.IsDepartmentMandatory);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.IsDepartmentMandatory);
				else
					this.IsDepartmentMandatory = base.SetboolAsString(ColumnNames.IsDepartmentMandatory, value);
			}
		}

		public virtual string s_IsAreaMandatory
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.IsAreaMandatory) ? string.Empty : base.GetboolAsString(ColumnNames.IsAreaMandatory);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.IsAreaMandatory);
				else
					this.IsAreaMandatory = base.SetboolAsString(ColumnNames.IsAreaMandatory, value);
			}
		}

		public virtual string s_IsBranchMandatory
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.IsBranchMandatory) ? string.Empty : base.GetboolAsString(ColumnNames.IsBranchMandatory);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.IsBranchMandatory);
				else
					this.IsBranchMandatory = base.SetboolAsString(ColumnNames.IsBranchMandatory, value);
			}
		}

		public virtual string s_IsGradeMandatory
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.IsGradeMandatory) ? string.Empty : base.GetboolAsString(ColumnNames.IsGradeMandatory);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.IsGradeMandatory);
				else
					this.IsGradeMandatory = base.SetboolAsString(ColumnNames.IsGradeMandatory, value);
			}
		}

		public virtual string s_IsLevelMandatory
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.IsLevelMandatory) ? string.Empty : base.GetboolAsString(ColumnNames.IsLevelMandatory);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.IsLevelMandatory);
				else
					this.IsLevelMandatory = base.SetboolAsString(ColumnNames.IsLevelMandatory, value);
			}
		}

		public virtual string s_IsJobTitleMandatory
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.IsJobTitleMandatory) ? string.Empty : base.GetboolAsString(ColumnNames.IsJobTitleMandatory);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.IsJobTitleMandatory);
				else
					this.IsJobTitleMandatory = base.SetboolAsString(ColumnNames.IsJobTitleMandatory, value);
			}
		}

		public virtual string s_IsGenderMandatory
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.IsGenderMandatory) ? string.Empty : base.GetboolAsString(ColumnNames.IsGenderMandatory);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.IsGenderMandatory);
				else
					this.IsGenderMandatory = base.SetboolAsString(ColumnNames.IsGenderMandatory, value);
			}
		}

		public virtual string s_IsAgeMandatory
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.IsAgeMandatory) ? string.Empty : base.GetboolAsString(ColumnNames.IsAgeMandatory);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.IsAgeMandatory);
				else
					this.IsAgeMandatory = base.SetboolAsString(ColumnNames.IsAgeMandatory, value);
			}
		}

		public virtual string s_IsDurationMandatory
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.IsDurationMandatory) ? string.Empty : base.GetboolAsString(ColumnNames.IsDurationMandatory);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.IsDurationMandatory);
				else
					this.IsDurationMandatory = base.SetboolAsString(ColumnNames.IsDurationMandatory, value);
			}
		}

		public virtual string s_IsRecentPromotionDateMandatory
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.IsRecentPromotionDateMandatory) ? string.Empty : base.GetboolAsString(ColumnNames.IsRecentPromotionDateMandatory);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.IsRecentPromotionDateMandatory);
				else
					this.IsRecentPromotionDateMandatory = base.SetboolAsString(ColumnNames.IsRecentPromotionDateMandatory, value);
			}
		}

		public virtual string s_SurveyTypeID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.SurveyTypeID) ? string.Empty : base.GetintAsString(ColumnNames.SurveyTypeID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.SurveyTypeID);
				else
					this.SurveyTypeID = base.SetintAsString(ColumnNames.SurveyTypeID, value);
			}
		}

		public virtual string s_Duration
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Duration) ? string.Empty : base.GetDateTimeAsString(ColumnNames.Duration);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Duration);
				else
					this.Duration = base.SetDateTimeAsString(ColumnNames.Duration, value);
			}
		}

		public virtual string s_IsGovernrateMandatory
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.IsGovernrateMandatory) ? string.Empty : base.GetboolAsString(ColumnNames.IsGovernrateMandatory);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.IsGovernrateMandatory);
				else
					this.IsGovernrateMandatory = base.SetboolAsString(ColumnNames.IsGovernrateMandatory, value);
			}
		}

		public virtual string s_ArHeader
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.ArHeader) ? string.Empty : base.GetstringAsString(ColumnNames.ArHeader);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.ArHeader);
				else
					this.ArHeader = base.SetstringAsString(ColumnNames.ArHeader, value);
			}
		}

		public virtual string s_EnHeader
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.EnHeader) ? string.Empty : base.GetstringAsString(ColumnNames.EnHeader);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.EnHeader);
				else
					this.EnHeader = base.SetstringAsString(ColumnNames.EnHeader, value);
			}
		}

		public virtual string s_ArFooter
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.ArFooter) ? string.Empty : base.GetstringAsString(ColumnNames.ArFooter);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.ArFooter);
				else
					this.ArFooter = base.SetstringAsString(ColumnNames.ArFooter, value);
			}
		}

		public virtual string s_EnFooter
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.EnFooter) ? string.Empty : base.GetstringAsString(ColumnNames.EnFooter);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.EnFooter);
				else
					this.EnFooter = base.SetstringAsString(ColumnNames.EnFooter, value);
			}
		}

		public virtual string s_EmailSubject
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.EmailSubject) ? string.Empty : base.GetstringAsString(ColumnNames.EmailSubject);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.EmailSubject);
				else
					this.EmailSubject = base.SetstringAsString(ColumnNames.EmailSubject, value);
			}
		}

		public virtual string s_EmailBody
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.EmailBody) ? string.Empty : base.GetstringAsString(ColumnNames.EmailBody);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.EmailBody);
				else
					this.EmailBody = base.SetstringAsString(ColumnNames.EmailBody, value);
			}
		}

		public virtual string s_SkipDemographicPage
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.SkipDemographicPage) ? string.Empty : base.GetboolAsString(ColumnNames.SkipDemographicPage);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.SkipDemographicPage);
				else
					this.SkipDemographicPage = base.SetboolAsString(ColumnNames.SkipDemographicPage, value);
			}
		}

		public virtual string s_ArEmailBody
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.ArEmailBody) ? string.Empty : base.GetstringAsString(ColumnNames.ArEmailBody);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.ArEmailBody);
				else
					this.ArEmailBody = base.SetstringAsString(ColumnNames.ArEmailBody, value);
			}
		}

		public virtual string s_IsPublic
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.IsPublic) ? string.Empty : base.GetboolAsString(ColumnNames.IsPublic);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.IsPublic);
				else
					this.IsPublic = base.SetboolAsString(ColumnNames.IsPublic, value);
			}
		}

		public virtual string s_IsCountryMandatory
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.IsCountryMandatory) ? string.Empty : base.GetboolAsString(ColumnNames.IsCountryMandatory);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.IsCountryMandatory);
				else
					this.IsCountryMandatory = base.SetboolAsString(ColumnNames.IsCountryMandatory, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter SurveyID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.SurveyID, Parameters.SurveyID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter ArName
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.ArName, Parameters.ArName);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter EnName
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.EnName, Parameters.EnName);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter ArDesc
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.ArDesc, Parameters.ArDesc);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter EnDesc
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.EnDesc, Parameters.EnDesc);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter CompanyID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.CompanyID, Parameters.CompanyID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter ExpiryDate
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.ExpiryDate, Parameters.ExpiryDate);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter IsDivisionMandatory
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.IsDivisionMandatory, Parameters.IsDivisionMandatory);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter IsDepartmentMandatory
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.IsDepartmentMandatory, Parameters.IsDepartmentMandatory);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter IsAreaMandatory
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.IsAreaMandatory, Parameters.IsAreaMandatory);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter IsBranchMandatory
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.IsBranchMandatory, Parameters.IsBranchMandatory);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter IsGradeMandatory
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.IsGradeMandatory, Parameters.IsGradeMandatory);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter IsLevelMandatory
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.IsLevelMandatory, Parameters.IsLevelMandatory);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter IsJobTitleMandatory
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.IsJobTitleMandatory, Parameters.IsJobTitleMandatory);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter IsGenderMandatory
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.IsGenderMandatory, Parameters.IsGenderMandatory);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter IsAgeMandatory
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.IsAgeMandatory, Parameters.IsAgeMandatory);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter IsDurationMandatory
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.IsDurationMandatory, Parameters.IsDurationMandatory);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter IsRecentPromotionDateMandatory
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.IsRecentPromotionDateMandatory, Parameters.IsRecentPromotionDateMandatory);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter SurveyTypeID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.SurveyTypeID, Parameters.SurveyTypeID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Duration
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Duration, Parameters.Duration);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter IsGovernrateMandatory
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.IsGovernrateMandatory, Parameters.IsGovernrateMandatory);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter ArHeader
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.ArHeader, Parameters.ArHeader);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter EnHeader
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.EnHeader, Parameters.EnHeader);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter ArFooter
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.ArFooter, Parameters.ArFooter);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter EnFooter
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.EnFooter, Parameters.EnFooter);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter EmailSubject
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.EmailSubject, Parameters.EmailSubject);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter EmailBody
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.EmailBody, Parameters.EmailBody);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter SkipDemographicPage
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.SkipDemographicPage, Parameters.SkipDemographicPage);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter ArEmailBody
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.ArEmailBody, Parameters.ArEmailBody);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter IsPublic
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.IsPublic, Parameters.IsPublic);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter IsCountryMandatory
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.IsCountryMandatory, Parameters.IsCountryMandatory);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter SurveyID
		    {
				get
		        {
					if(_SurveyID_W == null)
	        	    {
						_SurveyID_W = TearOff.SurveyID;
					}
					return _SurveyID_W;
				}
			}

			public WhereParameter ArName
		    {
				get
		        {
					if(_ArName_W == null)
	        	    {
						_ArName_W = TearOff.ArName;
					}
					return _ArName_W;
				}
			}

			public WhereParameter EnName
		    {
				get
		        {
					if(_EnName_W == null)
	        	    {
						_EnName_W = TearOff.EnName;
					}
					return _EnName_W;
				}
			}

			public WhereParameter ArDesc
		    {
				get
		        {
					if(_ArDesc_W == null)
	        	    {
						_ArDesc_W = TearOff.ArDesc;
					}
					return _ArDesc_W;
				}
			}

			public WhereParameter EnDesc
		    {
				get
		        {
					if(_EnDesc_W == null)
	        	    {
						_EnDesc_W = TearOff.EnDesc;
					}
					return _EnDesc_W;
				}
			}

			public WhereParameter CompanyID
		    {
				get
		        {
					if(_CompanyID_W == null)
	        	    {
						_CompanyID_W = TearOff.CompanyID;
					}
					return _CompanyID_W;
				}
			}

			public WhereParameter ExpiryDate
		    {
				get
		        {
					if(_ExpiryDate_W == null)
	        	    {
						_ExpiryDate_W = TearOff.ExpiryDate;
					}
					return _ExpiryDate_W;
				}
			}

			public WhereParameter IsDivisionMandatory
		    {
				get
		        {
					if(_IsDivisionMandatory_W == null)
	        	    {
						_IsDivisionMandatory_W = TearOff.IsDivisionMandatory;
					}
					return _IsDivisionMandatory_W;
				}
			}

			public WhereParameter IsDepartmentMandatory
		    {
				get
		        {
					if(_IsDepartmentMandatory_W == null)
	        	    {
						_IsDepartmentMandatory_W = TearOff.IsDepartmentMandatory;
					}
					return _IsDepartmentMandatory_W;
				}
			}

			public WhereParameter IsAreaMandatory
		    {
				get
		        {
					if(_IsAreaMandatory_W == null)
	        	    {
						_IsAreaMandatory_W = TearOff.IsAreaMandatory;
					}
					return _IsAreaMandatory_W;
				}
			}

			public WhereParameter IsBranchMandatory
		    {
				get
		        {
					if(_IsBranchMandatory_W == null)
	        	    {
						_IsBranchMandatory_W = TearOff.IsBranchMandatory;
					}
					return _IsBranchMandatory_W;
				}
			}

			public WhereParameter IsGradeMandatory
		    {
				get
		        {
					if(_IsGradeMandatory_W == null)
	        	    {
						_IsGradeMandatory_W = TearOff.IsGradeMandatory;
					}
					return _IsGradeMandatory_W;
				}
			}

			public WhereParameter IsLevelMandatory
		    {
				get
		        {
					if(_IsLevelMandatory_W == null)
	        	    {
						_IsLevelMandatory_W = TearOff.IsLevelMandatory;
					}
					return _IsLevelMandatory_W;
				}
			}

			public WhereParameter IsJobTitleMandatory
		    {
				get
		        {
					if(_IsJobTitleMandatory_W == null)
	        	    {
						_IsJobTitleMandatory_W = TearOff.IsJobTitleMandatory;
					}
					return _IsJobTitleMandatory_W;
				}
			}

			public WhereParameter IsGenderMandatory
		    {
				get
		        {
					if(_IsGenderMandatory_W == null)
	        	    {
						_IsGenderMandatory_W = TearOff.IsGenderMandatory;
					}
					return _IsGenderMandatory_W;
				}
			}

			public WhereParameter IsAgeMandatory
		    {
				get
		        {
					if(_IsAgeMandatory_W == null)
	        	    {
						_IsAgeMandatory_W = TearOff.IsAgeMandatory;
					}
					return _IsAgeMandatory_W;
				}
			}

			public WhereParameter IsDurationMandatory
		    {
				get
		        {
					if(_IsDurationMandatory_W == null)
	        	    {
						_IsDurationMandatory_W = TearOff.IsDurationMandatory;
					}
					return _IsDurationMandatory_W;
				}
			}

			public WhereParameter IsRecentPromotionDateMandatory
		    {
				get
		        {
					if(_IsRecentPromotionDateMandatory_W == null)
	        	    {
						_IsRecentPromotionDateMandatory_W = TearOff.IsRecentPromotionDateMandatory;
					}
					return _IsRecentPromotionDateMandatory_W;
				}
			}

			public WhereParameter SurveyTypeID
		    {
				get
		        {
					if(_SurveyTypeID_W == null)
	        	    {
						_SurveyTypeID_W = TearOff.SurveyTypeID;
					}
					return _SurveyTypeID_W;
				}
			}

			public WhereParameter Duration
		    {
				get
		        {
					if(_Duration_W == null)
	        	    {
						_Duration_W = TearOff.Duration;
					}
					return _Duration_W;
				}
			}

			public WhereParameter IsGovernrateMandatory
		    {
				get
		        {
					if(_IsGovernrateMandatory_W == null)
	        	    {
						_IsGovernrateMandatory_W = TearOff.IsGovernrateMandatory;
					}
					return _IsGovernrateMandatory_W;
				}
			}

			public WhereParameter ArHeader
		    {
				get
		        {
					if(_ArHeader_W == null)
	        	    {
						_ArHeader_W = TearOff.ArHeader;
					}
					return _ArHeader_W;
				}
			}

			public WhereParameter EnHeader
		    {
				get
		        {
					if(_EnHeader_W == null)
	        	    {
						_EnHeader_W = TearOff.EnHeader;
					}
					return _EnHeader_W;
				}
			}

			public WhereParameter ArFooter
		    {
				get
		        {
					if(_ArFooter_W == null)
	        	    {
						_ArFooter_W = TearOff.ArFooter;
					}
					return _ArFooter_W;
				}
			}

			public WhereParameter EnFooter
		    {
				get
		        {
					if(_EnFooter_W == null)
	        	    {
						_EnFooter_W = TearOff.EnFooter;
					}
					return _EnFooter_W;
				}
			}

			public WhereParameter EmailSubject
		    {
				get
		        {
					if(_EmailSubject_W == null)
	        	    {
						_EmailSubject_W = TearOff.EmailSubject;
					}
					return _EmailSubject_W;
				}
			}

			public WhereParameter EmailBody
		    {
				get
		        {
					if(_EmailBody_W == null)
	        	    {
						_EmailBody_W = TearOff.EmailBody;
					}
					return _EmailBody_W;
				}
			}

			public WhereParameter SkipDemographicPage
		    {
				get
		        {
					if(_SkipDemographicPage_W == null)
	        	    {
						_SkipDemographicPage_W = TearOff.SkipDemographicPage;
					}
					return _SkipDemographicPage_W;
				}
			}

			public WhereParameter ArEmailBody
		    {
				get
		        {
					if(_ArEmailBody_W == null)
	        	    {
						_ArEmailBody_W = TearOff.ArEmailBody;
					}
					return _ArEmailBody_W;
				}
			}

			public WhereParameter IsPublic
		    {
				get
		        {
					if(_IsPublic_W == null)
	        	    {
						_IsPublic_W = TearOff.IsPublic;
					}
					return _IsPublic_W;
				}
			}

			public WhereParameter IsCountryMandatory
		    {
				get
		        {
					if(_IsCountryMandatory_W == null)
	        	    {
						_IsCountryMandatory_W = TearOff.IsCountryMandatory;
					}
					return _IsCountryMandatory_W;
				}
			}

			private WhereParameter _SurveyID_W = null;
			private WhereParameter _ArName_W = null;
			private WhereParameter _EnName_W = null;
			private WhereParameter _ArDesc_W = null;
			private WhereParameter _EnDesc_W = null;
			private WhereParameter _CompanyID_W = null;
			private WhereParameter _ExpiryDate_W = null;
			private WhereParameter _IsDivisionMandatory_W = null;
			private WhereParameter _IsDepartmentMandatory_W = null;
			private WhereParameter _IsAreaMandatory_W = null;
			private WhereParameter _IsBranchMandatory_W = null;
			private WhereParameter _IsGradeMandatory_W = null;
			private WhereParameter _IsLevelMandatory_W = null;
			private WhereParameter _IsJobTitleMandatory_W = null;
			private WhereParameter _IsGenderMandatory_W = null;
			private WhereParameter _IsAgeMandatory_W = null;
			private WhereParameter _IsDurationMandatory_W = null;
			private WhereParameter _IsRecentPromotionDateMandatory_W = null;
			private WhereParameter _SurveyTypeID_W = null;
			private WhereParameter _Duration_W = null;
			private WhereParameter _IsGovernrateMandatory_W = null;
			private WhereParameter _ArHeader_W = null;
			private WhereParameter _EnHeader_W = null;
			private WhereParameter _ArFooter_W = null;
			private WhereParameter _EnFooter_W = null;
			private WhereParameter _EmailSubject_W = null;
			private WhereParameter _EmailBody_W = null;
			private WhereParameter _SkipDemographicPage_W = null;
			private WhereParameter _ArEmailBody_W = null;
			private WhereParameter _IsPublic_W = null;
			private WhereParameter _IsCountryMandatory_W = null;

			public void WhereClauseReset()
			{
				_SurveyID_W = null;
				_ArName_W = null;
				_EnName_W = null;
				_ArDesc_W = null;
				_EnDesc_W = null;
				_CompanyID_W = null;
				_ExpiryDate_W = null;
				_IsDivisionMandatory_W = null;
				_IsDepartmentMandatory_W = null;
				_IsAreaMandatory_W = null;
				_IsBranchMandatory_W = null;
				_IsGradeMandatory_W = null;
				_IsLevelMandatory_W = null;
				_IsJobTitleMandatory_W = null;
				_IsGenderMandatory_W = null;
				_IsAgeMandatory_W = null;
				_IsDurationMandatory_W = null;
				_IsRecentPromotionDateMandatory_W = null;
				_SurveyTypeID_W = null;
				_Duration_W = null;
				_IsGovernrateMandatory_W = null;
				_ArHeader_W = null;
				_EnHeader_W = null;
				_ArFooter_W = null;
				_EnFooter_W = null;
				_EmailSubject_W = null;
				_EmailBody_W = null;
				_SkipDemographicPage_W = null;
				_ArEmailBody_W = null;
				_IsPublic_W = null;
				_IsCountryMandatory_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter SurveyID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.SurveyID, Parameters.SurveyID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter ArName
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.ArName, Parameters.ArName);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter EnName
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.EnName, Parameters.EnName);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter ArDesc
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.ArDesc, Parameters.ArDesc);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter EnDesc
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.EnDesc, Parameters.EnDesc);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter CompanyID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.CompanyID, Parameters.CompanyID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter ExpiryDate
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.ExpiryDate, Parameters.ExpiryDate);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter IsDivisionMandatory
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.IsDivisionMandatory, Parameters.IsDivisionMandatory);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter IsDepartmentMandatory
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.IsDepartmentMandatory, Parameters.IsDepartmentMandatory);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter IsAreaMandatory
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.IsAreaMandatory, Parameters.IsAreaMandatory);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter IsBranchMandatory
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.IsBranchMandatory, Parameters.IsBranchMandatory);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter IsGradeMandatory
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.IsGradeMandatory, Parameters.IsGradeMandatory);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter IsLevelMandatory
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.IsLevelMandatory, Parameters.IsLevelMandatory);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter IsJobTitleMandatory
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.IsJobTitleMandatory, Parameters.IsJobTitleMandatory);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter IsGenderMandatory
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.IsGenderMandatory, Parameters.IsGenderMandatory);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter IsAgeMandatory
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.IsAgeMandatory, Parameters.IsAgeMandatory);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter IsDurationMandatory
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.IsDurationMandatory, Parameters.IsDurationMandatory);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter IsRecentPromotionDateMandatory
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.IsRecentPromotionDateMandatory, Parameters.IsRecentPromotionDateMandatory);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter SurveyTypeID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.SurveyTypeID, Parameters.SurveyTypeID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Duration
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Duration, Parameters.Duration);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter IsGovernrateMandatory
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.IsGovernrateMandatory, Parameters.IsGovernrateMandatory);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter ArHeader
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.ArHeader, Parameters.ArHeader);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter EnHeader
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.EnHeader, Parameters.EnHeader);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter ArFooter
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.ArFooter, Parameters.ArFooter);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter EnFooter
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.EnFooter, Parameters.EnFooter);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter EmailSubject
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.EmailSubject, Parameters.EmailSubject);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter EmailBody
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.EmailBody, Parameters.EmailBody);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter SkipDemographicPage
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.SkipDemographicPage, Parameters.SkipDemographicPage);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter ArEmailBody
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.ArEmailBody, Parameters.ArEmailBody);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter IsPublic
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.IsPublic, Parameters.IsPublic);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter IsCountryMandatory
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.IsCountryMandatory, Parameters.IsCountryMandatory);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter SurveyID
		    {
				get
		        {
					if(_SurveyID_W == null)
	        	    {
						_SurveyID_W = TearOff.SurveyID;
					}
					return _SurveyID_W;
				}
			}

			public AggregateParameter ArName
		    {
				get
		        {
					if(_ArName_W == null)
	        	    {
						_ArName_W = TearOff.ArName;
					}
					return _ArName_W;
				}
			}

			public AggregateParameter EnName
		    {
				get
		        {
					if(_EnName_W == null)
	        	    {
						_EnName_W = TearOff.EnName;
					}
					return _EnName_W;
				}
			}

			public AggregateParameter ArDesc
		    {
				get
		        {
					if(_ArDesc_W == null)
	        	    {
						_ArDesc_W = TearOff.ArDesc;
					}
					return _ArDesc_W;
				}
			}

			public AggregateParameter EnDesc
		    {
				get
		        {
					if(_EnDesc_W == null)
	        	    {
						_EnDesc_W = TearOff.EnDesc;
					}
					return _EnDesc_W;
				}
			}

			public AggregateParameter CompanyID
		    {
				get
		        {
					if(_CompanyID_W == null)
	        	    {
						_CompanyID_W = TearOff.CompanyID;
					}
					return _CompanyID_W;
				}
			}

			public AggregateParameter ExpiryDate
		    {
				get
		        {
					if(_ExpiryDate_W == null)
	        	    {
						_ExpiryDate_W = TearOff.ExpiryDate;
					}
					return _ExpiryDate_W;
				}
			}

			public AggregateParameter IsDivisionMandatory
		    {
				get
		        {
					if(_IsDivisionMandatory_W == null)
	        	    {
						_IsDivisionMandatory_W = TearOff.IsDivisionMandatory;
					}
					return _IsDivisionMandatory_W;
				}
			}

			public AggregateParameter IsDepartmentMandatory
		    {
				get
		        {
					if(_IsDepartmentMandatory_W == null)
	        	    {
						_IsDepartmentMandatory_W = TearOff.IsDepartmentMandatory;
					}
					return _IsDepartmentMandatory_W;
				}
			}

			public AggregateParameter IsAreaMandatory
		    {
				get
		        {
					if(_IsAreaMandatory_W == null)
	        	    {
						_IsAreaMandatory_W = TearOff.IsAreaMandatory;
					}
					return _IsAreaMandatory_W;
				}
			}

			public AggregateParameter IsBranchMandatory
		    {
				get
		        {
					if(_IsBranchMandatory_W == null)
	        	    {
						_IsBranchMandatory_W = TearOff.IsBranchMandatory;
					}
					return _IsBranchMandatory_W;
				}
			}

			public AggregateParameter IsGradeMandatory
		    {
				get
		        {
					if(_IsGradeMandatory_W == null)
	        	    {
						_IsGradeMandatory_W = TearOff.IsGradeMandatory;
					}
					return _IsGradeMandatory_W;
				}
			}

			public AggregateParameter IsLevelMandatory
		    {
				get
		        {
					if(_IsLevelMandatory_W == null)
	        	    {
						_IsLevelMandatory_W = TearOff.IsLevelMandatory;
					}
					return _IsLevelMandatory_W;
				}
			}

			public AggregateParameter IsJobTitleMandatory
		    {
				get
		        {
					if(_IsJobTitleMandatory_W == null)
	        	    {
						_IsJobTitleMandatory_W = TearOff.IsJobTitleMandatory;
					}
					return _IsJobTitleMandatory_W;
				}
			}

			public AggregateParameter IsGenderMandatory
		    {
				get
		        {
					if(_IsGenderMandatory_W == null)
	        	    {
						_IsGenderMandatory_W = TearOff.IsGenderMandatory;
					}
					return _IsGenderMandatory_W;
				}
			}

			public AggregateParameter IsAgeMandatory
		    {
				get
		        {
					if(_IsAgeMandatory_W == null)
	        	    {
						_IsAgeMandatory_W = TearOff.IsAgeMandatory;
					}
					return _IsAgeMandatory_W;
				}
			}

			public AggregateParameter IsDurationMandatory
		    {
				get
		        {
					if(_IsDurationMandatory_W == null)
	        	    {
						_IsDurationMandatory_W = TearOff.IsDurationMandatory;
					}
					return _IsDurationMandatory_W;
				}
			}

			public AggregateParameter IsRecentPromotionDateMandatory
		    {
				get
		        {
					if(_IsRecentPromotionDateMandatory_W == null)
	        	    {
						_IsRecentPromotionDateMandatory_W = TearOff.IsRecentPromotionDateMandatory;
					}
					return _IsRecentPromotionDateMandatory_W;
				}
			}

			public AggregateParameter SurveyTypeID
		    {
				get
		        {
					if(_SurveyTypeID_W == null)
	        	    {
						_SurveyTypeID_W = TearOff.SurveyTypeID;
					}
					return _SurveyTypeID_W;
				}
			}

			public AggregateParameter Duration
		    {
				get
		        {
					if(_Duration_W == null)
	        	    {
						_Duration_W = TearOff.Duration;
					}
					return _Duration_W;
				}
			}

			public AggregateParameter IsGovernrateMandatory
		    {
				get
		        {
					if(_IsGovernrateMandatory_W == null)
	        	    {
						_IsGovernrateMandatory_W = TearOff.IsGovernrateMandatory;
					}
					return _IsGovernrateMandatory_W;
				}
			}

			public AggregateParameter ArHeader
		    {
				get
		        {
					if(_ArHeader_W == null)
	        	    {
						_ArHeader_W = TearOff.ArHeader;
					}
					return _ArHeader_W;
				}
			}

			public AggregateParameter EnHeader
		    {
				get
		        {
					if(_EnHeader_W == null)
	        	    {
						_EnHeader_W = TearOff.EnHeader;
					}
					return _EnHeader_W;
				}
			}

			public AggregateParameter ArFooter
		    {
				get
		        {
					if(_ArFooter_W == null)
	        	    {
						_ArFooter_W = TearOff.ArFooter;
					}
					return _ArFooter_W;
				}
			}

			public AggregateParameter EnFooter
		    {
				get
		        {
					if(_EnFooter_W == null)
	        	    {
						_EnFooter_W = TearOff.EnFooter;
					}
					return _EnFooter_W;
				}
			}

			public AggregateParameter EmailSubject
		    {
				get
		        {
					if(_EmailSubject_W == null)
	        	    {
						_EmailSubject_W = TearOff.EmailSubject;
					}
					return _EmailSubject_W;
				}
			}

			public AggregateParameter EmailBody
		    {
				get
		        {
					if(_EmailBody_W == null)
	        	    {
						_EmailBody_W = TearOff.EmailBody;
					}
					return _EmailBody_W;
				}
			}

			public AggregateParameter SkipDemographicPage
		    {
				get
		        {
					if(_SkipDemographicPage_W == null)
	        	    {
						_SkipDemographicPage_W = TearOff.SkipDemographicPage;
					}
					return _SkipDemographicPage_W;
				}
			}

			public AggregateParameter ArEmailBody
		    {
				get
		        {
					if(_ArEmailBody_W == null)
	        	    {
						_ArEmailBody_W = TearOff.ArEmailBody;
					}
					return _ArEmailBody_W;
				}
			}

			public AggregateParameter IsPublic
		    {
				get
		        {
					if(_IsPublic_W == null)
	        	    {
						_IsPublic_W = TearOff.IsPublic;
					}
					return _IsPublic_W;
				}
			}

			public AggregateParameter IsCountryMandatory
		    {
				get
		        {
					if(_IsCountryMandatory_W == null)
	        	    {
						_IsCountryMandatory_W = TearOff.IsCountryMandatory;
					}
					return _IsCountryMandatory_W;
				}
			}

			private AggregateParameter _SurveyID_W = null;
			private AggregateParameter _ArName_W = null;
			private AggregateParameter _EnName_W = null;
			private AggregateParameter _ArDesc_W = null;
			private AggregateParameter _EnDesc_W = null;
			private AggregateParameter _CompanyID_W = null;
			private AggregateParameter _ExpiryDate_W = null;
			private AggregateParameter _IsDivisionMandatory_W = null;
			private AggregateParameter _IsDepartmentMandatory_W = null;
			private AggregateParameter _IsAreaMandatory_W = null;
			private AggregateParameter _IsBranchMandatory_W = null;
			private AggregateParameter _IsGradeMandatory_W = null;
			private AggregateParameter _IsLevelMandatory_W = null;
			private AggregateParameter _IsJobTitleMandatory_W = null;
			private AggregateParameter _IsGenderMandatory_W = null;
			private AggregateParameter _IsAgeMandatory_W = null;
			private AggregateParameter _IsDurationMandatory_W = null;
			private AggregateParameter _IsRecentPromotionDateMandatory_W = null;
			private AggregateParameter _SurveyTypeID_W = null;
			private AggregateParameter _Duration_W = null;
			private AggregateParameter _IsGovernrateMandatory_W = null;
			private AggregateParameter _ArHeader_W = null;
			private AggregateParameter _EnHeader_W = null;
			private AggregateParameter _ArFooter_W = null;
			private AggregateParameter _EnFooter_W = null;
			private AggregateParameter _EmailSubject_W = null;
			private AggregateParameter _EmailBody_W = null;
			private AggregateParameter _SkipDemographicPage_W = null;
			private AggregateParameter _ArEmailBody_W = null;
			private AggregateParameter _IsPublic_W = null;
			private AggregateParameter _IsCountryMandatory_W = null;

			public void AggregateClauseReset()
			{
				_SurveyID_W = null;
				_ArName_W = null;
				_EnName_W = null;
				_ArDesc_W = null;
				_EnDesc_W = null;
				_CompanyID_W = null;
				_ExpiryDate_W = null;
				_IsDivisionMandatory_W = null;
				_IsDepartmentMandatory_W = null;
				_IsAreaMandatory_W = null;
				_IsBranchMandatory_W = null;
				_IsGradeMandatory_W = null;
				_IsLevelMandatory_W = null;
				_IsJobTitleMandatory_W = null;
				_IsGenderMandatory_W = null;
				_IsAgeMandatory_W = null;
				_IsDurationMandatory_W = null;
				_IsRecentPromotionDateMandatory_W = null;
				_SurveyTypeID_W = null;
				_Duration_W = null;
				_IsGovernrateMandatory_W = null;
				_ArHeader_W = null;
				_EnHeader_W = null;
				_ArFooter_W = null;
				_EnFooter_W = null;
				_EmailSubject_W = null;
				_EmailBody_W = null;
				_SkipDemographicPage_W = null;
				_ArEmailBody_W = null;
				_IsPublic_W = null;
				_IsCountryMandatory_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_SurveyInsert]";
	
			CreateParameters(cmd);
			
			SqlParameter p;
			p = cmd.Parameters[Parameters.SurveyID.ParameterName];
			p.Direction = ParameterDirection.Output;
    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_SurveyUpdate]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_SurveyDelete]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.SurveyID);
			p.SourceColumn = ColumnNames.SurveyID;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.SurveyID);
			p.SourceColumn = ColumnNames.SurveyID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.ArName);
			p.SourceColumn = ColumnNames.ArName;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.EnName);
			p.SourceColumn = ColumnNames.EnName;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.ArDesc);
			p.SourceColumn = ColumnNames.ArDesc;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.EnDesc);
			p.SourceColumn = ColumnNames.EnDesc;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.CompanyID);
			p.SourceColumn = ColumnNames.CompanyID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.ExpiryDate);
			p.SourceColumn = ColumnNames.ExpiryDate;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.IsDivisionMandatory);
			p.SourceColumn = ColumnNames.IsDivisionMandatory;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.IsDepartmentMandatory);
			p.SourceColumn = ColumnNames.IsDepartmentMandatory;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.IsAreaMandatory);
			p.SourceColumn = ColumnNames.IsAreaMandatory;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.IsBranchMandatory);
			p.SourceColumn = ColumnNames.IsBranchMandatory;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.IsGradeMandatory);
			p.SourceColumn = ColumnNames.IsGradeMandatory;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.IsLevelMandatory);
			p.SourceColumn = ColumnNames.IsLevelMandatory;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.IsJobTitleMandatory);
			p.SourceColumn = ColumnNames.IsJobTitleMandatory;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.IsGenderMandatory);
			p.SourceColumn = ColumnNames.IsGenderMandatory;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.IsAgeMandatory);
			p.SourceColumn = ColumnNames.IsAgeMandatory;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.IsDurationMandatory);
			p.SourceColumn = ColumnNames.IsDurationMandatory;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.IsRecentPromotionDateMandatory);
			p.SourceColumn = ColumnNames.IsRecentPromotionDateMandatory;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.SurveyTypeID);
			p.SourceColumn = ColumnNames.SurveyTypeID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Duration);
			p.SourceColumn = ColumnNames.Duration;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.IsGovernrateMandatory);
			p.SourceColumn = ColumnNames.IsGovernrateMandatory;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.ArHeader);
			p.SourceColumn = ColumnNames.ArHeader;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.EnHeader);
			p.SourceColumn = ColumnNames.EnHeader;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.ArFooter);
			p.SourceColumn = ColumnNames.ArFooter;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.EnFooter);
			p.SourceColumn = ColumnNames.EnFooter;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.EmailSubject);
			p.SourceColumn = ColumnNames.EmailSubject;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.EmailBody);
			p.SourceColumn = ColumnNames.EmailBody;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.SkipDemographicPage);
			p.SourceColumn = ColumnNames.SkipDemographicPage;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.ArEmailBody);
			p.SourceColumn = ColumnNames.ArEmailBody;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.IsPublic);
			p.SourceColumn = ColumnNames.IsPublic;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.IsCountryMandatory);
			p.SourceColumn = ColumnNames.IsCountryMandatory;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
