
// Generated by MyGeneration Version # (1.3.0.3)

using System;
using GrowSurv.DAL;
namespace GrowSurv.BLL
{
	public class Answer : _Answer
	{
		public Answer()
		{
		
		}

        public virtual bool getAnswersByQuestionID(int questionID)
        {
            Where.QuestionID.Value = questionID;
            Where.QuestionID.Operator = MyGeneration.dOOdads.WhereParameter.Operand.Equal;
            return Query.Load();
        }
	}
}
