
// Generated by MyGeneration Version # (1.3.0.1)

using System;
using GrowSurv.DAL;
namespace GrowSurv.BLL
{
	public class Branch : _Branch
	{
		public Branch()
		{
		
		}

        public virtual bool GetListByCompanyID(int CompanyID)
        {
            Where.WhereClauseReset();
            Where.CompanyID.Value = CompanyID;
            return Query.Load();
        }

        public virtual bool GetActiveListByCompanyID(int CompanyID)
        {
            Where.WhereClauseReset();
            Where.CompanyID.Value = CompanyID;
            Where.IsActive.Value = true;
            return Query.Load();
        }
    }
}
