
// Generated by MyGeneration Version # (1.3.0.3)

using System;
using GrowSurv.DAL;
namespace GrowSurv.BLL
{
	public class Company : _Company
	{
		public Company()
		{
		
		}

        public virtual bool getCompanyByUsername(string username)
        {
            this.Where.Username.Value = username;
            return this.Query.Load();
        }

        public virtual bool searchCompany(string filterTxt)
        {
           string query = string.Format(@"SELECT U.*, mem.UserId,  mem.Username MemUserName, mem.lastactivitydate, m.IsLockedOut, m.IsApproved
                                        from 
                                        aspnet_Users mem  
                                        left join aspnet_membership m on mem.userid =m.userid 
                                        inner join Company u on u.username = mem.username                                    
                                         WHERE  ((mem.UserName LIKE N'%{0}%') OR (u.EnName LIKE N'%{0}%') OR (u.Email LIKE N'%{0}%')) and (U.IsDeleted <> 1 or U.IsDeleted is null)", filterTxt);
            return LoadFromRawSql(query);

        }

        public virtual bool searchCompanyForUsers(string filterTxt)
        {
            string query = string.Format(@"SELECT U.*, mem.UserId,  mem.Username MemUserName, mem.lastactivitydate, m.IsLockedOut, m.IsApproved
                                        from 
                                        aspnet_Users mem  
                                        left join aspnet_membership m on mem.userid =m.userid 
                                        left join Company u on u.username = mem.username                                    
                                         WHERE  ((mem.UserName LIKE N'%{0}%') OR (u.EnName LIKE N'%{0}%') OR (u.Email LIKE N'%{0}%')) and (U.IsDeleted <> 1 or U.IsDeleted is null)", filterTxt);
            return LoadFromRawSql(query);

        }
    }
}
