
// Generated by MyGeneration Version # (1.3.0.3)

using System;
using GrowSurv.DAL;
namespace GrowSurv.BLL
{
	public class DivisionWeight : _DivisionWeight
	{
		public DivisionWeight()
		{
		
		}

        public virtual bool DivisionBySurveyID(int surveyID, int companyID)
        {
            string query = string.Format(@"SELECT G.*, W.Weight, W.WeightID
                                            FROM Division G left Join DivisionWeight w on g.DivisionID = w.DivisionID and w.surveyID = {0} 
                                         where G.companyID = {1} and G.isActive = 1", surveyID, companyID);
            return LoadFromRawSql(query);

        }
    }
}
