
// Generated by MyGeneration Version # (1.3.0.3)

using System;
using GrowSurv.DAL;
namespace GrowSurv.BLL
{
	public class GenderWeight : _GenderWeight
	{
		public GenderWeight()
		{
		
		}

        public virtual bool GenderBySurveyID(int surveyID, int companyID)
        {
            string query = string.Format(@"SELECT G.*, W.Weight, W.WeightID
                                            FROM Gender G left Join GenderWeight w on g.GenderID = w.GenderID and w.surveyID = {0} ", surveyID, companyID);
            return LoadFromRawSql(query);

        }
    }
}
