
// Generated by MyGeneration Version # (1.3.0.3)

using System;
using GrowSurv.DAL;
namespace GrowSurv.BLL
{
	public class GovernrateWeight : _GovernrateWeight
	{
		public GovernrateWeight()
		{
		
		}

        public virtual bool GovBySurveyID(int surveyID, int companyID)
        {
            string query = string.Format(@"SELECT G.*, W.Weight, W.WeightID
                                            FROM Governrate G left Join governrateWeight w on g.GovernrateID = w.GovernrateID and w.surveyID = {0} 
                                         where G.companyID = {1} and G.isActive = 1", surveyID, companyID);
            return LoadFromRawSql(query);
            
        }
    }
}
