
// Generated by MyGeneration Version # (1.3.0.3)

using System;
using GrowSurv.DAL;
namespace GrowSurv.BLL
{
	public class Grade : _Grade
	{
		public Grade()
		{
		
		}


        public virtual bool GetListByCompanyID(int CompanyID)
        {
            Where.WhereClauseReset();
            Where.CompanyID.Value = CompanyID;
            return Query.Load();
        }

        public virtual bool GetActiveListByCompanyID(int CompanyID)
        {
            Where.WhereClauseReset();
            Where.CompanyID.Value = CompanyID;
            Where.IsActive.Value = true;
            return Query.Load();
        }
    }
}
