
// Generated by MyGeneration Version # (1.3.0.3)

using System;
using GrowSurv.DAL;
namespace GrowSurv.BLL
{
	public class JobTitleWeight : _JobTitleWeight
	{
		public JobTitleWeight()
		{
		
		}

        public virtual bool JobTitleBySurveyID(int surveyID, int companyID)
        {
            string query = string.Format(@"SELECT G.*, W.Weight, W.WeightID
                                            FROM JobTitle G left Join JobTitleWeight w on g.JobTitleID = w.JobTitleID and w.surveyID = {0} 
                                         where G.companyID = {1} and G.isActive = 1", surveyID, companyID);
            return LoadFromRawSql(query);

        }
    }
}
