
// Generated by MyGeneration Version # (1.3.0.3)

using System;
using GrowSurv.DAL;
namespace GrowSurv.BLL
{
	public class LevelWeight : _LevelWeight
	{
		public LevelWeight()
		{
		
		}

        public virtual bool LevelBySurveyID(int surveyID, int companyID)
        {
            string query = string.Format(@"SELECT G.*, W.Weight, W.WeightID
                                            FROM Level G left Join levelWeight w on g.LevelID = w.LevelID and w.surveyID = {0} 
                                         where G.companyID = {1} and G.isActive = 1", surveyID, companyID);
            return LoadFromRawSql(query);

        }
    }
}
