
// Generated by MyGeneration Version # (1.3.0.3)

using System;
using GrowSurv.DAL;
using System.Collections.Specialized;
using System.Data.SqlClient;
using System.Data;

namespace GrowSurv.BLL
{
	public class Question : _Question
	{
		public Question()
		{
		
		}

        public virtual bool searchQuestions(string filtertxt, int SurveyID)
        {
            string query = string.Format(@"SELECT U.*, S.EnName QuestionTypeName
                                        from Question u inner join QuestionType S  on S.QuestionTypeID = u.QuestionTypeID                                                              
                                    WHERE  ((U.EnTitle LIKE N'%{0}%') OR (u.ArTitle LIKE N'%{0}%')) and (u.SurveyID = {1} or {1} = 0) order by u.questionorder", filtertxt, SurveyID);
            return LoadFromRawSql(query);
        }

        public virtual bool GetMainBranchSurveyQuestions(int surveyID)
        {
            ListDictionary parameters = new ListDictionary();
            parameters.Add(new SqlParameter("@SurveyID", SqlDbType.Int, 0), surveyID);
            return LoadFromSql("GetMainBranchSurveyQuestions", parameters);
        }

        public virtual bool GetSurveyQuestionsByBranchIDAndSurveyID(int surveyID, int? BranchID)
        {
            ListDictionary parameters = new ListDictionary();
            parameters.Add(new SqlParameter("@SurveyID", SqlDbType.Int, 0), surveyID);
            parameters.Add(new SqlParameter("@BranchID", SqlDbType.Int, 0), BranchID.HasValue ? BranchID.Value : 0);
            return LoadFromSql("GetSurveyQuestionsByBranchIDAndSurveyID", parameters);
        }

        public virtual bool GetSurveyQuestionsByBranchIDAndSurveyIDAndCategoryID(int surveyID, int BranchID,int CategoryID )
        {
            ListDictionary parameters = new ListDictionary();
            parameters.Add(new SqlParameter("@SurveyID", SqlDbType.Int, 0), surveyID);
            parameters.Add(new SqlParameter("@BranchID", SqlDbType.Int, 0), BranchID);
            parameters.Add(new SqlParameter("@CategoryID", SqlDbType.Int, 0), CategoryID);
            return LoadFromSql("GetSurveyQuestionsByBranchIDAndSurveyIDAndCategoryID", parameters);
        }

        

        public virtual bool GetSurveyQuestionsByBranchID(int BranchID)
        {
            ListDictionary parameters = new ListDictionary();
            parameters.Add(new SqlParameter("@BranchID", SqlDbType.Int, 0), BranchID);
            return LoadFromSql("GetSurveyQuestionsByBranchID", parameters);
        }

        public virtual bool GetSubQuestionsByQuestionID(int QuestionID)
        {            
            Where.ParentQuestionID.Value = QuestionID;
            Where.ParentQuestionID.Operator = MyGeneration.dOOdads.WhereParameter.Operand.Equal;
            return Query.Load();
        }

        public virtual bool GetSurveyQuestionsBySurveyIDAndCategoryID(int surveyID, int CategoryID)
        {
            ListDictionary parameters = new ListDictionary();
            parameters.Add(new SqlParameter("@SurveyID", SqlDbType.Int, 0), surveyID);
            parameters.Add(new SqlParameter("@CategoryID", SqlDbType.Int, 0), CategoryID);
            return LoadFromSql("GetSurveyQuestionsBySurveyIDAndCategoryID", parameters);
        }
        

    }
}
