
// Generated by MyGeneration Version # (1.3.0.3)

using System;
using GrowSurv.DAL;

namespace GrowSurv.BLL
{
	public class SupportTicket : _SupportTicket
	{
		public SupportTicket()
		{
		    
		}

        public virtual bool getSupportTicketsForAdmin()
        {
            string query = string.Format(@"SELECT *,U.UserName UserName
                                            FROM SupportTicket ST Join aspnet_Users U on ST.UserID = U.UserId
                                            where ST.IsDeleted != 1 OR ST.IsDeleted is null");
            return LoadFromRawSql(query);
        }

        public virtual bool getSupportTicketsForClient(string UserID )
        {
            string query = string.Format(@"SELECT *
                                            FROM SupportTicket ST 
                                            where (ST.IsDeleted != 1 OR ST.IsDeleted is null)
                                            AND UserID = '{0}'", UserID);
            return LoadFromRawSql(query);
        }

    }
}
