
// Generated by MyGeneration Version # (1.3.0.1)

using System;
using GrowSurv.DAL;
namespace GrowSurv.BLL
{
	public class SurveyMemberAnswer : _SurveyMemberAnswer
	{
		public SurveyMemberAnswer()
		{
		
		}

        public virtual bool getAnswerByMemberIDAndQuestionID(int memberID, int questionID)
        {
            Where.WhereClauseReset();
            Where.SurveyMemberID.Value = memberID;
            Where.QuestionID.Value = questionID;
            return Query.Load();
        }

        public virtual bool getSurveyMemberAnswerByQuestionID(int questionID)
        {
            Where.WhereClauseReset();
            Where.QuestionID.Value = questionID;
            return Query.Load();
        }
    }
}
